### ISSUE TITLE
additive & dynamic search facets

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#106]
Would be great to be able to mix & match search filters a la Amazon/Newegg and other e-commerce sites.

<img width="592" alt="screen shot 2015-09-29 at 11 50 11 am" src="https://cloud.githubusercontent.com/assets/919583/10171545/492d477c-66a0-11e5-9283-91aeddfc8eb1.png">

Looks like the haystack API supports this, we just need to whip up some javascript/UI to make it interactive.

**Comment by cathydeng** [comment]
implemented via https://github.com/datamade/django-councilmatic/commit/56d4648dc28818df89ff43dab4d41a54b69cac02
