### ISSUE TITLE
dynamic rich snippets

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#107]
All rich snippets are hard coded to the same thing. These should be dynamic based on the page that is shared (legislation, event, person, committee, etc)

Here's what it looks like now:

<img width="734" alt="screen shot 2015-09-29 at 12 00 54 pm" src="https://cloud.githubusercontent.com/assets/919583/10171860/d2febcf0-66a1-11e5-957b-bc2a5354c2c9.png">

**Comment by cathydeng** [comment]
imo this should go in django-councilmatic

**Comment by derekeder** [comment]
good call. can you move it over there?
