### ISSUE TITLE
more central placement of bill status button

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#112]
Just a suggestion, haven't done user testing yet. On Intro pages :: 

http://nyc.councilmatic.org/legislation/int-643-2015/

... I think the Status button is too far right, a bit out of the path of my eye. 

Could we try to the left or right of 'currently controlled by' info? Totally good with whatever you think.

**Comment by cathydeng** [comment]
made the status label larger, so that it's the most visually prominent thing on bill detail pages
