### ISSUE TITLE
show primary bill sponsor on search page

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#113]
<img width="813" alt="screen shot 2015-10-03 at 12 36 01 pm" src="https://cloud.githubusercontent.com/assets/919583/10264233/6b438b7c-69cb-11e5-89fe-8d61b3042c9b.png">

**Comment by cathydeng** [comment]
closed via https://github.com/datamade/django-councilmatic/commit/92365ba1946c9b76d54f558b16471528412199f0
