### ISSUE TITLE
next city council meeting not updating based on current date

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#115]
Home page was showing the 9/30 council meeting when it was after 9/30.

**Comment by derekeder** [comment]
It is now showing a past council meeting as well as past upcoming meetings 
<img width="1029" alt="screen shot 2015-10-12 at 8 58 03 am" src="https://cloud.githubusercontent.com/assets/919583/10429655/cad835c4-70bf-11e5-98ad-31b843df3dac.png">

**Comment by cathydeng** [comment]
fixed via 95d5e80711a79a0ab5cc7ece34a30f7550e71f09
