### ISSUE TITLE
Live or no?

### ISSUE THREAD

**Issue by jooltman** [datamade/nyc-councilmatic#116]
Hello,
I saw your presentation at Beta NYC CfASummit recap, and am eager to use your site, but can't find it live anywhere. Any tips? I "try" to use Legistar regularly, and would love to help you refine your product.

**Comment by derekeder** [comment]
Hi @jooltman! Yes the site is live at http://nyc.councilmatic.org/

Our Google Juice isn't so great yet, but we'll be shooting to get on that first page of 'nyc legislation' and the like.

**Comment by davidmooreppf** [comment]
Hi @jooltman - just adding, I'm based in NYC, working out of Civic Hall, and happy to chat more. My email is david at ppolitics.org, and you can DM me on my ppolitics Twitter account anytime. Would love to have your feedback on the site, and your help in bringing it to CB 6 and other community groups. Let us know what you think, really appreciate your interest. (Have we met at old OpenPlans office before, possibly? I know the Streetsblog NYC folks from there. Cool.)
