### ISSUE TITLE
checking on timing for capturing events of intros

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#117]
This Intro was in the buzzz ::

https://twitter.com/bradlander/status/654728037020205064

.. shows w/ three actions on Legistar on the 14th :: 

http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=1681071&GUID=0561BAD3-8683-408D-A4DB-565FAC20438C&Options=ID%7CText%7C&Search=154

... if the scrapers ran last night, would actions display here on Intro 154 of 2014 page? 

http://nyc.councilmatic.org/legislation/int-154-2014/

... might be to do with version -A mentioned in Brad's Tweet and on Legistar in the column? I haven't tried searching a lot but haven't seen a lot of -A versions on NYC Councilmatic. Can do more research in a bit but have to hop offline now. 

cc @fgregg

**Comment by cathydeng** [comment]
the legistar site has versions (e.g. *, A) attached to bill actions but councilmatic doesn't have the concept of bill versions - all actions would just live in [introduction 154-2014](http://nyc.councilmatic.org/legislation/int-154-2014/) regardless of version. we just re-loaded data, so all the actions in legistar are also on the councilmatic bill pages.

**Comment by derekeder** [comment]
@davidmooreppf also, we noticed the Legistar scraper was running and finishing **after** the website was updating, so things were about a day behind.

We are updating the cron tasks so the scraper has time to finish before the website update.

**Comment by davidmooreppf** [comment]
Looks good! Makes sense.
