### ISSUE TITLE
Disqus - adding me as primary moderator or site admin

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#120]
OK, using this issue to walk through a few commenting tweaks. Derek, are you primary moderator for the  councilmatic.org Disqus instance? Can we to transfer it to me? Or adding me as Site Admin is fine too. 

Info, if helpful: [changing primary moderator](https://help.disqus.com/customer/en/portal/articles/654999-how-do-i-change-the-primary-moderator-). My Disqus username is davidmooreppf; email is drm at ppolitics.org. 

I'll be implementing pre-moderation under Admin -> Engage -> Community Rules, is the goal, before launching public comment program at this early stage. Happy to chat while you do this - interested in seeing what copy is displayed, informing new commenters of the time involved.

**Comment by davidmooreppf** [comment]
Just a ping on this, would be good to turn on pre-moderation on Disqus today, if possible.

**Comment by derekeder** [comment]
@davidmooreppf thanks for the nudge. Pre-moderation is now turned on. Looking into the admin transfer now.

**Comment by derekeder** [comment]
@davidmooreppf transferring ownership is possible, but it might just be easier for you to set up your own Disqus account (its free) and we can update the website. I believe we don't have any comments on there that aren't from us, right?

**Comment by davidmooreppf** [comment]
Sorry just getting back to this. Yep my Disqus username was above, tied to my primary work email address: davidmooreppf. 

That was just intended to be the fastest immediate solution. Separate issue will be to create emails for me at Councilmatic and a moderator at Councilmatic. 

So where do comments go now? Tried a second test one, there's a note about moderation, but didn't get a notification to drm at ppolitics email. Can chat if easier.

**Comment by davidmooreppf** [comment]
So where do comment moderation alerts go now, and can they go to Disqus: davidmooreppf? 

I assume the email notifications will link to the Disqus dashboard. I forget what our old one on OG was like. 

Looking to make a sample comment forum on an Intro page for outreach follow-ups to council offices, and this would let me create that.

**Comment by davidmooreppf** [comment]
All right, to [manage comments](https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-), need "to register your site and install Disqus on your site using the shortname registered."

My Disqus shortname tied to username davidmooreppf is: askthem. But I don't yet see Councilmatic in my [drop-down](https://www.dropbox.com/s/2ob2qybijkaikpk/Screenshot%202015-11-09%2007.13.13.png?dl=0) of sites, and I don't see a plus-sign to add more. 

I registered a second Disqus username: davidrussellmoore, which does not yet have a shortname because I haven't yet [registered a site](https://www.dropbox.com/s/0ee864ucnoftso3/Screenshot%202015-11-09%2007.15.15.png?dl=0) with it. 

Let me know how to proceed, whether to simply get davidmooreppf able to moderate Councilmatic, or how to fill out the unique Disqus URL if that's easier. 

Not to get too confusing, but as in #123, I'm hoping for all Disqus comments to be pre-moderated at admin@councilmatic.org. So maybe we need to do that first.

**Comment by derekeder** [comment]
Ok new disqus config setup and deployed!
