### ISSUE TITLE
create new email accounts for site outreach & moderation

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#123]
Related to #120, given we have email address info@, can we please create: 

david@councilmatic.org - for me

asher@councilmatic.org - for @ashernovek 

admin@councilmatic.org - for moderation 

... and then we'll set up Disqus moderator with the admin@, to forward to both david@ and asher@.

**Comment by derekeder** [comment]
created admin@councilmatic that forwards to david & asher
