### ISSUE TITLE
council members' email addresses are out of date at the source

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#124]
On [CM Rodgriuez's Councilmatic page](http://nyc.councilmatic.org/person/ydanis-a-rodriguez/), email is the old one still listed on his [Legistar page](http://legistar.council.nyc.gov/PersonDetail.aspx?ID=38927&GUID=2357CC08-0EE6-4325-90B0-4F8CD700BC96). 

The other [council profile page](http://council.nyc.gov/d10/html/members/home.shtml) has it as yrodriguez at council etc., we should update it to that, please. 

The general issue here is I should go through and ensure members' emails reflect the more up-to-date council.nyc.gov.

**Comment by derekeder** [comment]
@davidmooreppf seems like the place to fix it would be at the source. Can we notify the Clerk's office to update their info? As soon as it updates, we'll get it on Councilmatic.

**Comment by reginafcompton** [comment]
Not a Councilmatic issue. Closing!
