### ISSUE TITLE
add counts atop member pages of sponsorship and co-sponsored items

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#127]
On [member pages](http://nyc.councilmatic.org/person/antonio-reynoso/), add count up top, e.g.: 

21 sponsored items, 47 co-sponsored items to date in current 2014-2017 session. View all 68 together. 

The 21 could link to its own view, the 47 could link to its own view, and the 68 to its combined view on /search. 

And below, on the member's page, could still be the list of primary sponsored items, as current.  This is an option for accomplishing #125, of course, which can be nuked if this is the way forward.

**Comment by derekeder** [comment]
Agreed this would be useful. Should we add these counts back to the search page facets as well?

**Comment by davidmooreppf** [comment]
On old [OC member](https://www.opencongress.org/people/show/412402_Steve_Womack) pages, we had: "10 Sponsored Bills (Ranks 181 of 439) 0 Made Into Law (Ranks 51 of 439)" - but I feel like that's too inaccurate a portrait of city council dynamics. For more-distant federal members, it got few complaints.

**Comment by cathydeng** [comment]
@davidmooreppf what do you think about changing the search to only primary sponsorships for a given council member? it seems like primary sponsorships are the most relevant, since there are so many co-sponsorships. what's the use case for searching on co-sponsorships?

**Comment by cathydeng** [comment]
related to #125
