### ISSUE TITLE
event times display an hour later than Legistar primary source

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#129]
Affects cmte. hearings & stated meetings, both. Time zones, yes, ET vs. CT? 

1:30 pm ET: http://legistar.council.nyc.gov/MeetingDetail.aspx?ID=440356&GUID=3EC5EB40-64B1-43BA-BDA6-4C1BFC7143B0&Options=info&Search=

2:30 pm ET: http://nyc.councilmatic.org/event/440356/

...etc. Can pull up more links if helpful.

**Comment by cathydeng** [comment]
fixed by @evz!
