### ISSUE TITLE
add bill-related documents

### ISSUE THREAD

**Issue by cathydeng** [datamade/nyc-councilmatic#13]
- [x] add to models
- [x] load documents when loading bills in the loadata management command

**Comment by fgregg** [comment]
Hmm... I thought I fixed this. Could you point me to an example.

**Comment by cathydeng** [comment]
ya it's fine on ocd, just not in this django app yet

**Comment by fgregg** [comment]
oh, okay.

**Comment by fgregg** [comment]
This has been added as of https://github.com/opencivicdata/scrapers-us-municipal/pull/59
