### ISSUE TITLE
question about bringing over full bill text from Legistar, when short

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#130]
Intro 788 is relevant to AirBNB discussion in NYC. 

On [Legistar](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2286841&GUID=A24E5D98-591E-48D0-BC33-ED235D7DDC8E&Options=ID%7cText%7c&Search=788), there are two paragraphs of full text. 

On [Councilmatic](http://nyc.councilmatic.org/legislation/int-788-2015/), summary is there in full, but there's no full text tab. Just wondering why, maybe it's too short? Ha.  

Closely related intros such as 826 - on [Legistar](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2352289&GUID=BD8F4E03-725E-4457-973E-2927CDBB9337) & [Councilmatic](http://nyc.councilmatic.org/legislation/int-826-2015/) - do have full text.

**Comment by fgregg** [comment]
Hmm.. the full text is not in the API.
http://ocd.datamade.us/ocd-bill/f6bd34e5-2b20-487d-b98b-1c2110174b38/

I'll look into it.

On Wed, Dec 2, 2015 at 10:42 AM, David Moore notifications@github.com
wrote:

> Intro 788 is relevant to AirBNB discussion in NYC.
> 
> On Legistar
> http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2286841&GUID=A24E5D98-591E-48D0-BC33-ED235D7DDC8E&Options=ID%7cText%7c&Search=788,
> there are two paragraphs of full text.
> 
> On Councilmatic http://nyc.councilmatic.org/legislation/int-788-2015/,
> summary is there in full, but there's no full text tab. Just wondering why,
> maybe it's too short? Ha.
> 
> Closely related intros such as 826 - on Legistar
> http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2352289&GUID=BD8F4E03-725E-4457-973E-2927CDBB9337
> & Councilmatic http://nyc.councilmatic.org/legislation/int-826-2015/ -
> do have full text.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/130.

## 

773.888.2718
