### ISSUE TITLE
Add extended Discourse Oneboxing support

### ISSUE THREAD

**Issue by jqnatividad** [datamade/nyc-councilmatic#131]
So beyond the synopsis with generic oneboxing that councilmatic already supports, we can get more detailed info (e.g. status of bill, etc.)

**Comment by fgregg** [comment]
I don't know what oneboxing means. Can you explain?

**Comment by jqnatividad** [comment]
see https://talk.beta.nyc/t/airbnb-to-release-its-nyc-data-by-appointment-only/1783/10
and https://talk.beta.nyc/t/discourse-what-is-oneboxing/1789

**Comment by fgregg** [comment]
Interesting! Thanks for the info.

On Thu, Dec 3, 2015 at 10:53 AM, Joel Natividad notifications@github.com
wrote:

> see
> https://talk.beta.nyc/t/airbnb-to-release-its-nyc-data-by-appointment-only/1783/10
> and https://talk.beta.nyc/t/discourse-what-is-oneboxing/1789
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/131#issuecomment-161713012
> .

## 

773.888.2718

**Comment by fgregg** [comment]
For additional context when evaluating this issue, we have gotten less than 5 visits originating on a Discourse site in the last month.

**Comment by jqnatividad** [comment]
Will see if I can do a PR over the weekend.  Its relatively straightforward to implement - basically, just tweaking the Opengraph or Oembed metadata tags to give more contextual info.  Added bonus of making Facebook and SEO links better too so its not just for Discourse.

For more indepth integration ala Twitter, Github, Youtube, Wikipedia, etc., one will need to create a onebox engine - https://github.com/discourse/onebox

**Comment by fgregg** [comment]
Cool! If you do want to make that PR, you should probably do it on https://github.com/datamade/django-councilmatic/blob/3ae7eaafdae2eb6184c866dddf08c52f0335797f/councilmatic_core/templates/partials/seo.html

**Comment by jqnatividad** [comment]
Will do!

Long term, you may want to look into tighter Discourse integration... unlike Disqus, you own the content, it has integrated search and auto-suggestions, you can do categories, it doubles as a mailing list, and has a robust API https://meta.discourse.org/t/discourse-api-documentation/22706
cc @davidmooreppf

**Comment by cathydeng** [comment]
closing this since it's an enhancement & would make more sense in django-councilmatic
