### ISSUE TITLE
Disqus not displaying on legislative item pages

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#132]
Seems Disqus is not displaying on all [Intro pages](http://nyc.councilmatic.org/legislation/int-210-2014/?view=comments) site-wide, same with [other leg. types](http://nyc.councilmatic.org/legislation/t-2015-3777/?view=comments), in Chrome & Safari.

It's possible this has been the case for two days? Thought I had checked a bill page since Wed. but perhaps not. 

Something w/ JS? See this in the page source, ha :: 

```
                <noscript> Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a> </noscript>
```

**Comment by cathydeng** [comment]
hm, odd. looking into it

**Comment by davidmooreppf** [comment]
Just a ping on this, would be good to have back this week.

**Comment by cathydeng** [comment]
hey @davidmooreppf! fixed this in councilmatic core (django-councilmatic) today. waiting until later tonight when traffic dies down to deploy, because some other councilmatic core updates will require wiping out events for half an hour ish

**Comment by davidmooreppf** [comment]
cool thx

**Comment by cathydeng** [comment]
fixed via https://github.com/datamade/django-councilmatic/commit/119428f30888b57d7fcb7ec985e923e7d5bf53c0
