### ISSUE TITLE
check legislation scrapers - Intros in December on Legistar, but not Councilmatic

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#134]
So, looking into why the Freelancers Bill, [intro 1017](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2530972&GUID=61F8754B-80AF-493E-895E-D6D17209776E&Options=ID|Text|&Search=ls+5314), intro'd last week isn't found on Councilmatic, either by number "[1017](http://nyc.councilmatic.org/search/?q=1017)" or keyword "freelance workers". 

I don't know if we pull from this page as a primary source, but here's Brad Lander on [Legistar](http://legistar.council.nyc.gov/PersonDetail.aspx?ID=42518&GUID=FEE6A879-4718-4990-AFD0-F68A96269855), and on [Councilmatic](http://nyc.councilmatic.org/person/brad-s-lander/) - Intro 1017 isn't on former, of course. But it is findable on main NYC Legistar search, for 1017, [introduced](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2530972&GUID=61F8754B-80AF-493E-895E-D6D17209776E&Options=ID%7cText%7c&Search=1017) on the 7th.

Looking at the minutes from that stated meeting, it also included Intro 128 - couldn't find that one on Legistar - also Intro 609, that's on [Legistar](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2119778&GUID=E12FA77F-832A-48CC-96B6-0231AB028D1C&Options=ID|Text|&Search=609) and also on [Councilmatic](http://nyc.councilmatic.org/legislation/int-609-2015/). 

So, something about 1017's actions? I can't permalink to the results but if you do Legistar Advanced Search for on-agenda on 12/7, it's there in the list of 23 items. Partial [screenshot](https://www.dropbox.com/s/x5ah000586jutnn/Screenshot%202015-12-17%2018.42.33.png?dl=0) of Legistar search results. But Intro 1014, to pick one at random, is in Legistar but not [Councilmatic](http://nyc.councilmatic.org/search/?q=1014).

Yesterday was another full council stated meeting - 61 items on Legistar, including intro 1040, which is on [Legistar](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2537076&GUID=DA939434-D8C3-4B98-B0BE-C5211C632491&Options=Advanced&Search=) but not on [Councilmatic](http://nyc.councilmatic.org/search/?q=1040).

Happy to research more, let me know how to help. I can check

**Comment by fgregg** [comment]
Hmm... okay. It's getting hung on on this vote event

http://legistar.council.nyc.gov/HistoryDetail.aspx?ID=11174708&GUID=09E172AB-B981-4BF1-8247-01846EFCB68A

Particularly on the vote option 'paternity'

Any idea what's going on there?

On Thu, Dec 17, 2015 at 5:45 PM, David Moore notifications@github.com
wrote:

> Assigned #134 https://github.com/datamade/nyc-councilmatic/issues/134
> to @fgregg https://github.com/fgregg.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/134#event-495308786.

## 

773.888.2718

**Comment by davidmooreppf** [comment]
Will find out tmw from contacts in Council. He does Participatory Budgeting, but I don't know him or his staff closely yet... I mean, if "paternity leave" of some sort affected the scraping, that's remarkably cool.

**Comment by fgregg** [comment]
Oooh! That would make sense.

On Thu, Dec 17, 2015 at 8:50 PM, David Moore notifications@github.com
wrote:

> Will find out tmw from contacts in Council. He does Participatory
> Budgeting, but I don't know him or his staff closely yet... I mean, if
> "paternity leave" of some sort affected the scraping, that's remarkably
> cool.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/134#issuecomment-165654850
> .

## 

773.888.2718

**Comment by davidmooreppf** [comment]
I was initially thinking the more highly technical parent-child dynamic code models, of course. High high level stuff brought way down and then way back up.

**Comment by davidmooreppf** [comment]
Some initial contacts didn't know the answer, but they're looking into it - seems likely it was data entry error. Anyway, what kind of answer is needed? How can we bring in Intro 1017?

**Comment by fgregg** [comment]
Hmm.. it's in the API
http://ocd.datamade.us/bills/?from_organization=ocd-organization/0f63aae8-16fd-4d3c-b525-00747a482cf9&identifier=Int%201017-2015

@cathydeng this will probably get loaded tomorrow?

On Fri, Dec 18, 2015 at 4:08 PM, David Moore notifications@github.com
wrote:

> Some initial contacts didn't know the answer, but they're looking into it
> - seems likely it was data entry error. Anyway, what kind of answer is
>   needed? How can we bring in Intro 1017?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/134#issuecomment-165908344
> .

## 

773.888.2718

**Comment by cathydeng** [comment]
yeah the task runs in the morning. i can go in manually and load it now, since the loaddata task no longer needs to delete existing data

**Comment by cathydeng** [comment]
kk 1017 is on the site now: http://nyc.councilmatic.org/legislation/int-1017-2015/
