### ISSUE TITLE
checking on event scrapers - 2016 is still hidden behind sort-by on Legistar

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#136]
Just getting around to checking event scraping - the [Legistar calendar page](http://legistar.council.nyc.gov/Calendar.aspx) still has 2015 as default, so 2016 is behind drop-down, ha. 

I see just now that there are events on Legistar this month for 2016, so I'll inquire when they're flipping the switch on their end to 2016. Then we should get them in - there's no unique URL for 2016 that I see. 

We could export them to Excel but they'll come through when the page flips, so to type. Will update.

**Comment by derekeder** [comment]
@davidmooreppf this issue is unrelated to the legistar form. There was an issue with the OCD server running out of disk space, which we have since resolved. We expect the data to update properly by tomorrow.

**Comment by fgregg** [comment]
These updated this morning!
