### ISSUE TITLE
checking on event agenda scraping - did stated council meeting link switch today?

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#137]
First [stated meeting](http://nyc.councilmatic.org/event/448793/) of 2016 was today. 

Our Councilmatic page links to this incorrect URL for the agenda, gives an error on Legistar :: 

http://legistar.council.nyc.gov/View.ashx?M=A&ID=448793&GUID=0CC07F49-1806-4F95-A4A4-8F38FE952A2A

Correct agenda, linked off Legistar [Calendar](http://legistar.council.nyc.gov/Calendar.aspx) listing :: 

http://legistar.council.nyc.gov/View.ashx?M=A&ID=454697&GUID=D00638D6-4658-480E-9BAA-CB271DDCB1CD

---

Committee hearing agendas seem to be working fine, I tried two of them to check. 

Link on Finance Cmte. hearing today from Councilmatic ::

http://legistar.council.nyc.gov/View.ashx?M=A&ID=452726&GUID=2A845580-1B15-4E79-B52A-85C97D679952

Same URL on Legistar ::

http://legistar.council.nyc.gov/View.ashx?M=A&ID=452726&GUID=2A845580-1B15-4E79-B52A-85C97D679952

So maybe they changed the stated meeting agenda link today? If we think so, and if it's difficult to run the scraper before stated meetings, maybe we should un-link the agenda on our end? 

Let me know if I should ask our contacts at Council.

**Comment by fgregg** [comment]
They must have changed the url for the agenda after 5am this morning. I'm not sure what the best thing to do about this is.

We can't really scrape more often.

We may be able to cache the agenda, but then we could have outdated agendas. I don't think that's better than having broken agenda links.

**Comment by davidmooreppf** [comment]
If / when the NYC Legistar API ever exists, current agendas may be included. 

For now, I'll make a new issue to fix it in the code - to look for the text "stated meetings" in Event, and display a link to Legistar for most-current official agenda.
