### ISSUE TITLE
for stated council meeting Events, link to Legistar for official agenda

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#138]
Building off #137, is it possible to write a rule as below for agendas? Not priority for now. 

For Events that have text [Stated Meeting](http://nyc.councilmatic.org/event/448793/), link to official Legistar [Calendar](http://legistar.council.nyc.gov/Calendar.aspx) page, with sample text under Attachments next to Agenda :: 

Stated meeting agendas are usually published the morning of the meeting and are likely to change in advance - for the latest version, see the agenda published on the official NYC legislative calendar.

**Comment by fgregg** [comment]
Great solution!

On Wed, Jan 6, 2016 at 3:56 PM, David Moore notifications@github.com
wrote:

> Building off #137
> https://github.com/datamade/nyc-councilmatic/issues/137, is it possible
> to write a rule as below for agendas? Not priority for now.
> 
> For Events that have text Stated Meeting
> http://nyc.councilmatic.org/event/448793/, link to official Legistar
> Calendar http://legistar.council.nyc.gov/Calendar.aspx page, with
> sample text under Attachments next to Agenda ::
> 
> Stated meeting agendas are usually published the morning of the meeting
> and are likely to change in advance - for the latest version, see the
> agenda published on the official NYC legislative calendar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/138.

## 

773.888.2718
