### ISSUE TITLE
Data all with scrape method or admin web interface to?

### ISSUE THREAD

**Issue by johnfelipe** [datamade/nyc-councilmatic#140]

**Comment by cathydeng** [comment]
hi @johnfelipe - we load all the data from the open civic data api using the loaddata management command. we populate the ocd api separately, by scraping. what are you looking to do?

**Comment by johnfelipe** [comment]
I want create an instance for colombia council / assembly / parliament

**Comment by cathydeng** [comment]
ok - councilmatic consumes data from open civic data, so populating that from existing legislative data would be the first step. the scrapers for various cities in the us are here: https://github.com/datamade/municipal-scrapers-us

i'm not sure how well the data models will translate to colombia, though. are you doing this work with a particular organization?

**Comment by davidmooreppf** [comment]
Hi JohnFelipe, I'm happy to connect over Skype or video chat to discuss more - I know a bit about parliamentary monitoring tech going back to our work on OpenCongress and more. Add me Skype and we can arrange a time to chat more? I'm davidmooreppf, happy to help. Here's an [old spreadsheet](https://docs.google.com/spreadsheets/d/1kbvYBB9rUmKIClthzzn0e2QnigdJP9rs7JSoZEjYoys/edit?hl=en#gid=0) with a long list of previous projects, and maybe you'd like to connect with the community through NDI's [Opening Parliament](http://www.openingparliament.org/).

**Comment by johnfelipe** [comment]
Is for arauca assembly
http://actas.asambleadelosaraucanos.co
I need something for keeping tabs deputies and all
My skype is john.felipe.urrego.mejia
Stay alert
David i send u invitation
![screenshot_2016-01-08-18-51-45](https://cloud.githubusercontent.com/assets/428820/12212478/eafb8856-b638-11e5-863f-a5511e4fab11.png)
