### ISSUE TITLE
get nyc councilmatic on most recent version of django-councilmatic

### ISSUE THREAD

**Issue by cathydeng** [datamade/nyc-councilmatic#143]
addresses & closes #142

**Comment by cathydeng** [comment]
some things to check:
- [x] jurisdiction settings
- [x] some committee pages are broken
- [x] make sure search still works
- [x] try out loaddata
- [x] add content to `ABOUT_BLURBS`

**Comment by evz** [comment]
Closed with 75a23b1b889da89bd21d93b47e8da5bf9369bb3b
