### ISSUE TITLE
mockup (image only) of alert feature placement on Committee page

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#146]
For our Knight Cities [proposal](http://www.participatorypolitics.org/councilmatic-a-finalist-in-knight-cities-challenge/), I included the super dumb [Skitch image](http://www.participatorypolitics.org/wp-content/uploads/2016/01/Housing_Cmte_Councilmatic_alerts.png) of how alerts could be placed on Cmte. pages.

We can include one image with the proposal - Cathy, do you have time before Saturday afternoon to do a better-looking version of the above? Just an image is fine, it doesn't need to be on site that's online - for example, on a Chicago [cmte. page](https://chicago.councilmatic.org/committee/committee-on-housing-and-real-estate/)? 

If you're occupied all day today, or if this doesn't seem like a good use of time, I can do a mockup in Balsamiq that'll be fine, but I figured I'd ask to see if this works in your bandwidth today. Just one image, a .jpg, is the goal. I'll be in this D.C. meeting all afternoon but happy to chat here in the issue or tmw during the day as well. cc @derekeder

**Comment by cathydeng** [comment]
@davidmooreppf sure, I can do a mockup in html of what it could look like - I'll send it over this evening. I wouldn't place it where it is in the skitch image, since that's only going to work on wide screens, but I'll play around.

**Comment by davidmooreppf** [comment]
Cool - yeah the Skitch was obvs just a placeholder. Thx.

Email & SMS are necessary, the social media row was just a thought, maybe just a little Twitter icon is enough for that. It would be good to someday find a way to automate Twttr feeds for cmte. meetings.

**Comment by cathydeng** [comment]
here ya go:

<img width="916" alt="screen shot 2016-01-28 at 5 33 50 pm" src="https://cloud.githubusercontent.com/assets/1406537/12662357/77f6c908-c5e5-11e5-978a-c93079b00ba4.png">

<img width="913" alt="screen shot 2016-01-28 at 5 29 18 pm" src="https://cloud.githubusercontent.com/assets/1406537/12662359/7ab91c2c-c5e5-11e5-9901-5ea4200e869d.png">

**Comment by davidmooreppf** [comment]
Looks great, thanks!
