### ISSUE TITLE
Council Member map broken?

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#147]
All tiles don't seem to load and map is unresponsive: http://nyc.councilmatic.org/council-members/

<img width="1264" alt="screen shot 2016-02-01 at 10 35 36 am" src="https://cloud.githubusercontent.com/assets/919583/12723588/a1032fac-c8cf-11e5-9c22-90d8a7189bb2.png">

**Comment by davidmooreppf** [comment]
Address lookup is unresponsive as well, as probably expected - would be good to have this fixed by Monday Feb. 8th, as I have a big MeetUp on the 9th.

**Comment by cathydeng** [comment]
@davidmooreppf it looks like this will be solved when we get everything updated to work with the most recent django-councilmatic. it's almost ready! will def be fixed by Mon

**Comment by evz** [comment]
Closed with https://github.com/datamade/django-councilmatic/commit/f78475b6e7a47050d2dc1b994854f86a3471ad44
