### ISSUE TITLE
question on data source for NYC council member lookup

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#148]
Answering an email question - which solution did you use for NYC member lookup on [/council-members](http://nyc.councilmatic.org/council-members/)? 

There's the trusty League of Women Voters' [site](http://blog.cartodb.com/guest-post-new-online-service-who-represents-me/), and misc. on NYC open data [portal](https://data.cityofnewyork.us/data?cat=city%20government). 

Maybe Cathy or Evz.

**Comment by derekeder** [comment]
We downloaded the boundaries and imported them into our Open Civic Data API endpoint. From there we import it to the web app, which is what you see on the map.

For the address search, we geocode using Google and then use [leaflet-pip](https://github.com/mapbox/leaflet-pip) to find the right district.

Anything to add @evz?

**Comment by evz** [comment]
That's about it.
