### ISSUE TITLE
[support] Routing issue when setting up a local instance

### ISSUE THREAD

**Issue by patcon** [datamade/nyc-councilmatic#150]
I had all the data imported following the README instructions, but when I went to `runserver`, the page that loaded had no theming.
- no css or imagery
- all assets return 500 errors
- all link paths return 301 back to main page

gist with the output of various troubleshooting commands: https://gist.github.com/patcon/416f27b9aa5c55d89d25

Any idea what the root of this might be. As shown in the gist, it doesn't appear to be a file permissions issue. For what it's worth, I've run other django projects just fine.

Screenshot: https://imgur.com/LujAS2c

Slack context: https://opencivicdata.slack.com/archives/councilmatic/p1454628114000068

**Comment by cathydeng** [comment]
in settings.py, you should set DEBUG to True for local development, & the static assets will show up. if DEBUG = False, you have to run python manage.py collectstatic to get all the static assets

**Comment by patcon** [comment]
Could we default that to True in the example file? Seems someone running in production will be more experienced and not get bitten, but first-timers might have a bad spell on their first go as-is :)

**Comment by patcon** [comment]
Or alternatively, if we want to be more defensive with regards to folks in production, we could use this in the README instead of the `cp` step:

```
cd councilmatic
cat settings_deployment.py.example | sed 's/DEBUG = False/DEBUG = True/' > settings_deployment.py
```

**Comment by patcon** [comment]
Great! Your suggestions got me up and running, and I submitted them as PR to help out the next person: https://github.com/datamade/nyc-councilmatic/pull/149
