### ISSUE TITLE
use greyscale map on council member detail

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#152]
With the upgraded `leaflet-google.js`, we need to pass in the map style config to change the default Google tile styles 

<img width="279" alt="screen shot 2016-02-05 at 4 32 11 pm" src="https://cloud.githubusercontent.com/assets/919583/12861042/241e71fe-cc26-11e5-9645-96ca26c142a8.png">

**Comment by cathydeng** [comment]
fixed via https://github.com/datamade/django-councilmatic/commit/b94b2c23b1507aa158e63178b5811afc11341e81
