### ISSUE TITLE
one homepage feature update Feb. 

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#153]
For top Featured Legislation, replacing taxi bill, let's go with new Freelancers bill.

For image, let's try their protest image - we can crop this if need be?  

https://d3q437fqezjn6j.cloudfront.net/content/uploads/zinnia/2016/01/28/fl-41.jpg

Headline: Freelance Isn't Free bill from Freelancers Union 

On December 7th, along with 26 city council co-sponsors, Freelancers Union introduced the "#freelanceisntfree" bill. This is the nation's first proposed legislation protecting NYC's 1.3 million freelancers against client nonpayment. Clients who do not provide a contract, are late to pay, or fail to pay a freelancer for work can be sued. The bill's public hearing in the Consumer Affairs committee will be Monday, Feb 29th, at 1pm at City Hall.

links to: https://nyc.councilmatic.org/legislation/int-1017-2015/
### 

The police body cameras bill can stay as-is.

**Comment by cathydeng** [comment]
it'd be great to add some hyperlinks to this blurb. some things to hyperlink:
- "Freelancers Union"
- "#freelanceisntfree" (should this be a link to the twitter hashtag search?)
- "proposed legislation" (perhaps a relevant news article)

@davidmooreppf can you find these?

also I'm gona shorten the headline to just 'Freeland Isn't Free' to save space

**Comment by davidmooreppf** [comment]
Totally. In order: 

https://www.freelancersunion.org/

https://www.freelancersunion.org/advocacy/

https://www.washingtonpost.com/news/wonk/wp/2015/12/07/for-freelancers-getting-stiffed-is-part-of-the-job-some-in-new-york-city-want-to-fix-it/
