### ISSUE TITLE
one bill featured on homepage not displaying 

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#154]
Not urgent. Homepage [intro 607 of 2014](https://nyc.councilmatic.org/legislation/int-607-2014/) not loading. Amusingly, also removes "Meetings" from top nav, ha, and the site logo. Site logo appears fine on cmte. and member profile pages. 

Other bill pages seem fine. If anything shows in error logs or whatever, I did think I ran into some errors with Legislation filters during a demo an hour ago, but I can't replicate them now. 

Bill page on [Legistar](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2103584&GUID=632A9A91-7FD5-424A-880D-7A4E0A8AD0B2&Options=ID|Text|&Search=607) is still up, no recent actions shown.

**Comment by cathydeng** [comment]
fixed via https://github.com/datamade/nyc-councilmatic/commit/2b175449013b005cb97e917861ceb1a9683e7dd9
