### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#158]
Let's add RSS feeds for the following views:
- [x] all events
- [x] committee actions
- [x] individual bills - actions taken
- [x] any search, new/updated legislation
- [x] council member, sponsored bills

**Comment by mccc** [comment]
@davidmooreppf : I'm working on the RSS feed(s) for Committees. Does it make more sense to implement:
- An RSS feed of the most recent committee actions
- An RSS feed of past and upcoming committee events
- Both (combined into one RSS feed)
- Both (as separate RSS feeds)

?

**Comment by mccc** [comment]
I've currently implemented feeds for Committee Members, Committees (Actions and Events), Faceted Searches; I will add one for actions on Bills shortly.

**Comment by derekeder** [comment]
RSS is now deployed on both NYC and Chicago Councilmatics!

@mccc these are looking good!
