### ISSUE TITLE
Embedable widgets

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#159]
Create a set of embeddable widgets for sharing on third party sites.

These widgets may include views for:
- individual legislation
- individual council members
- committee overview
- recently passed legislation

@davidmooreppf more user input is required before building these out. do you have any potential partners in NYC who would be interested in embedding a widget on their website? We should talk to them

**Comment by derekeder** [comment]
@davidmooreppf we're going to be getting to these in the next week or two. it would be useful to know from you / your target audience what kind of widgets would be useful.

The most obvious one to me is a legislation widget that news outlets & community orgs can drop in their site when talking about a particular bill.

I could also see council members wanting to embed their detail page on their website. Some questions there as to what info they'd like to see. Recent bills? District map? Some kind of score card?

**Comment by davidmooreppf** [comment]
Seeing this, will type more, but in short - yes, I think we should cover legislative intros, but then I think council member widgets would be second priority. Will check with local media partners later this afternoon even.

**Comment by davidmooreppf** [comment]
Just a quick note confirming that our media partners said we have the priority right. 

All straightforward, as you were surely already on-path to include, as much of below as is feasible in space allowed. Hunh, I wonder if formatting will look all right below, can move to G-doc easily. 
1. Individual legislative items - i.e., intro’s 
   a) Number
   b) Primary Sponsor 
   c) Total sponsors
   d) Committee
   e) Last action
2. Individual council members
   a) District number 
   b) Profile photo
   c) Neighborhood names might get too long, n'est-ce pas? 
3. Committee overview
   a) Chair
   b) Number of members
   c) Next meeting scheduled date 
   d) Active intros might be too misleading to excerpt, n'est-ce pas? 
4. Recently passed legislation - pretty much as in stream from bottom of NYC homepage and as in one above. 

Misc. ideas :: 
- Neighborhood news - e.g. District widgets by neighborhood name, “East Harlem”
- Events schedule - all forthcoming meetings council-wide
- Active legislation - intro’s sponsored by cmte. Chairs, or with more than a few sponsors

I'll try to pull up some comparable politician info cards from federal & state levels, from around. Some previous civic tech companies providing widgets have transitioned out of the service.

**Comment by cathydeng** [comment]
started widgets for bills, people, & committees. on the [staging site](https://nyc-staging.councilmatic.org/), you can see them by adding `widget/` to the end of any bill/person/committee page url.

here's a screenshot of what it could look like embedded in a news article:
<img width="683" alt="screen shot 2016-05-10 at 1 34 19 pm" src="https://cloud.githubusercontent.com/assets/1406537/15158323/03974bc0-16b5-11e6-8785-3fc51f9a059a.png">

**Comment by derekeder** [comment]
These are done and deployed on NYC and Chicago!
