### ISSUE TITLE
check bill scraping re: date of most recent action

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#163]
User submitted issue - I'll research this a bit more. 

Legistar page, Intro 463-A, most recent action: 2/29/16 :: http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=1891009&GUID=D2E74CB2-75AC-4479-AC5B-0854708379E3&Options=&Search=

Councilmatic page for same Intro number, links to 463-A same URL on Legistar, but doesn't have most recent date of action, and doesn't show "version A" on page  - not sure if that's relevant or not:: https://nyc.councilmatic.org/legislation/int-463-2014/

... it does have committee report from 2/29/16 though. And correct number of sponsors. But it doesn't show as "version A" when searching by number from /search, either. "A" is amended, by the way. 

I'll check if other bills with recent actions are showing correctly on NYC Councilmatic, or if the verison A detail is relevant. Just putting this through now while thinking of it.

**Comment by fgregg** [comment]
A new type of "vote" (jury duty) was throwing off the scraper. I just fixed
and kicked off manually. If the problem still persists tomorrow, let me
know.
