### ISSUE TITLE
'Inactive' legislation renders invisibly

### ISSUE THREAD

**Issue by mccc** [datamade/nyc-councilmatic#169]
E.g. https://nyc.councilmatic.org/legislation/res-85-2014/ is Inactive, but the 'Inactive' label
( `<span class="label label-inactive">Inactive</span>` ) is rendered invisible for some reason. The same thing happens on search results which have inactive legislation.

**Comment by cathydeng** [comment]
oh yeah, that was intentional - the council members didn't want the label next to inactive bills, so we just made the inactive label invisible (but kept the inactive status in the search filters).

related to https://github.com/datamade/nyc-councilmatic/issues/128
