### ISSUE TITLE
capture official title of bills

### ISSUE THREAD

**Issue by cathydeng** [datamade/nyc-councilmatic#17]

**Comment by derekeder** [comment]
On the legislation detail page, it looks like we have a few useful things we can capture, in addition to title:

On http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2286807&GUID=F4D39B04-3039-4FC3-9090-A7F28F01B3DE
- File #:   M 0281-2015
- Name:     Submitting the Proposed City FY'16 Community Development Program, the Proposed CFY'16 Budget, the Proposed Reallocations-the CD XLI Funds, Proposed CD XLII Statement of Objectives and Budget, dated 5/7/15.
- Type:     Mayor's Message
- Title:    Communication from the Mayor - Submitting the Proposed City Fiscal Year 2016 Community Development Program, the Proposed CFY'16 Budget, the Proposed Reallocations-the CD XLI Funds, Proposed CD XLII Statement of Objectives and Budget, dated May 7, 2015.

**Comment by fgregg** [comment]
I don't know what you are are asking for.

We are capturing everything there except "Name" which is short version of
the official tile (and often very uninformative)

**Comment by derekeder** [comment]
Hmm looking at http://api.opencivicdata.org/ocd-bill/1505cfc8-83f3-47dc-aaf8-582d8977064a/

I don't see type or file #

**Comment by fgregg** [comment]
File # is "identifier"

**Comment by fgregg** [comment]
You are right about type... I'll add that.

**Comment by derekeder** [comment]
Cool. I see File #.

Regarding name, I think we should capture it. This seems much more informative:

Zoning, Tres Puentes - 285 East 138TH ST, Bronx (C 150288 ZMX)

vs

Application No. C 150288 ZMX submitted by the West Side Federation for Senior and Supportive Housing pursuant to Section 197-c and 201 of the New York City Charter, for an amendment of the Zoning Map, Section No. 6a, changing an R6 District to an R7-2 District, establishing within an existing R6 District a C1-4 District, establishing within a proposed R7-2 District a C1-4 District, and establishing within a proposed R7-2 District a C2-4 District, on property generally bounded by Third Avenue, 139th Street, Alexander Avenue, and 138th Street, Borough of the Bronx, Community Board 1, Council District 8.

Either way, we can't use the current title as the legislation title unless we truncate it. It looks like this:

<img width="823" alt="screen shot 2015-08-13 at 5 17 25 pm" src="https://cloud.githubusercontent.com/assets/919583/9263019/30c4a5bc-41df-11e5-99b4-16e2c9fd21ea.png">

**Comment by fgregg** [comment]
We can capture name, but it is often not informative at all. Often it's
something like 'land use application'

**Comment by fgregg** [comment]
also, that long title **is** the official title, see
https://github.com/datamade/municipal-scrapers-us/issues/17#issuecomment-126032027

**Comment by davidmooreppf** [comment]
Can chat options - I should have mentioned this two days ago in response to forrest in #17 - 

Colloquially, leg. objects are known as, e.g., "Local Law 11 of 2012" -- [example](http://www.nyc.gov/html/doitt/html/open/local_law_11_2012.shtml) - i.e., by the "Introduction" file number.

So for me, the ideal solution would be for the above-mentioned object's page on Councilmatic to show the red h1 heading in Chicago version: "Communication from the Mayor 0281-2015". 

Or another example, "Local Law 757-2014". Official [Legistar page](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2015556&GUID=1CB2BD89-B975-4B62-B225-1ACDA495C354&Options=ID|Text|&Search=540).

Is the h1 where the OCD title feeds into, in the code? Can chat voice, but have to move locations now.

**Comment by davidmooreppf** [comment]
W/r/t [OCD title](http://docs.opencivicdata.org/en/latest/api/search.html#bill-search) - can the API serve the NYC legislative object file number, and display that in the page h1? 

I don't mean to confuse what will display on a page heading w/ the data model, realize they're separate issues.

**Comment by derekeder** [comment]
@davidmooreppf agree, and thanks for sharing that term definition list on nyc.gov. I think going with a combination of type and file # is a good idea for the title.

However, I'm a bit confused as to how we can derive "Local Law 757-2014" from this [Legistar page](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2015556&GUID=1CB2BD89-B975-4B62-B225-1ACDA495C354&Options=ID|Text|&Search=540) you linked to.

On there I see:
Type: Introduction
File #: Int 0540-2014

So wouldn't we call it "Introduction Int 0540-2014"? Am I missing something?

**Comment by davidmooreppf** [comment]
You're correct, it would be, "Introduction 540-2014", or "Introduction 540 of 2014". The example I chose happened to be of an intro that passed as a Local Law.

**Comment by fgregg** [comment]
These have been added as of https://github.com/opencivicdata/scrapers-us-municipal/pull/59 (make take a while to get into OCD)

**Comment by davidmooreppf** [comment]
From a leg. staffer, just for reference - we'll talk this week over what's poss. to display - basically, "Intro 540-2014" seems best to display prominently on page. 

---

If the bill is awaiting a hearing ("introduced") or awaiting a vote ("laid over in committee") we just call it "Intro 540" or written out as "Int. 540-2014". If it's a resolution, than spoken as "Reso 540" or written as "Res. 540-2014". If this bill were to pass this year it would be "Local law 540 of 2015" or written as "LL 2015/52".

**Comment by fgregg** [comment]
We are capturing the official title, the name, and the local classification.
