### ISSUE TITLE
add permalink to URL in widgets

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#172]
In [widget](http://www.participatorypolitics.org/test-widgets/), there's not a permalink to the item itself, viz. the bill intro. 

There's a top banner permalink to homepage, and the sponsor and controlling body are hyperlinked, but not the Intro title itself.

Seems like hyperlinking Intro title or member name or committee name would be best, assuming possible? Back to URL, e.g. :: https://nyc.councilmatic.org/legislation/int-1017-2015. Or, a bottom link >> would be fine, if that can't be linked for some reason. 

Feel free to reassign to whoever. cc @cathydeng

**Comment by davidmooreppf** [comment]
Gooood morning team. Just seeing if this might be able to be in bandwidth today.

**Comment by cathydeng** [comment]
hey @davidmooreppf! I'll tackle the linking this afternoon

**Comment by cathydeng** [comment]
fixed via https://github.com/datamade/django-councilmatic/commit/e4238a8282fd72be913be67e91e6e22136844e88 & deployed to the live site

**Comment by davidmooreppf** [comment]
Awesome, thanks. Great.
