### ISSUE TITLE
Fix "Controlling Body" facet filter bug

### ISSUE THREAD

**Issue by patcon** [datamade/nyc-councilmatic#173]
Something funny is going on with "Controlling Body" facet filtering.

New York City Council filter works fine:
https://nyc.councilmatic.org/search/?selected_facets=controlling_body_exact%3ANew%20York%20City%20Council

But every other controlling body filter is broken, and displays no results:
https://nyc.councilmatic.org/search/?selected_facets=controlling_body_exact%3A%20Environmental%20Protection

**Comment by reginafcompton** [comment]
Fixed. See Issue #181
