### ISSUE TITLE
resolution scraping up-to-date?

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#174]
Looking for [Res 1104](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2745754&GUID=1E10FC9E-D09D-4691-A4BC-D523E7C2514E&Options=ID|Text|&Search=1104), not found through /search or on our [Rules Cmte.](https://nyc.councilmatic.org/committee/committee-on-rules-privileges-and-elections/) page. I'll be back online in an hour to do a deeper check around res scraping. Background on [Fast Co](http://www.fastcompany.com/3060906/to-improve-public-comments-on-proposed-laws-nyc-lawmakers-seek-online-feedback).

**Comment by fgregg** [comment]
It's in the API.
http://ocd.datamade.us/ocd-bill/89446653-120a-46e6-b3be-b8d442ced04e/ attn
@cathydeng
