### ISSUE TITLE
Link to event RSS?

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#175]
On the events page, I don't see a way to get to the events RSS: https://nyc.councilmatic.org/events/

Related to #158

**Comment by reginafcompton** [comment]
This is fixed.

<img width="769" alt="screen shot 2016-10-27 at 3 21 20 pm" src="https://cloud.githubusercontent.com/assets/13078679/19783844/17ee4f4a-9c59-11e6-8645-01dbfb57fca2.png">
