### ISSUE TITLE
Instructions on how to share widgets

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#177]
Thanks to #159, we now have widgets for:
- Council Members: https://nyc.councilmatic.org/person/margaret-s-chin/widget/
- Legislation: https://nyc.councilmatic.org/legislation/int-662-2015/widget/
- Committees: https://nyc.councilmatic.org/committee/committee-on-aging/widget/

@cathydeng are there others? Recently passed legislation?

We should add instructions on each of these pages on how to share these widgets. Twitter does a pretty good job at this:

first:

<img width="626" alt="screen shot 2016-06-14 at 5 35 10 pm" src="https://cloud.githubusercontent.com/assets/919583/16062054/64287894-3256-11e6-98d2-37f0d04ab1b7.png">

then:

<img width="524" alt="screen shot 2016-06-14 at 5 35 18 pm" src="https://cloud.githubusercontent.com/assets/919583/16062058/682e69ee-3256-11e6-96b6-50c483237fa4.png">

Perhaps some kind of button that displays a [bootstrap modal](http://getbootstrap.com/javascript/#modals) with similar instructions?

**Comment by reginafcompton** [comment]
This is done. See here.

<img width="1268" alt="screen shot 2016-10-31 at 10 16 22 am" src="https://cloud.githubusercontent.com/assets/13078679/19859394/23f5575a-9f53-11e6-9a30-4c75cd849569.png">
