### ISSUE TITLE
Left-cascading filter count badges when Chrome zoom is at 75%

### ISSUE THREAD

**Issue by mccc** [datamade/nyc-councilmatic#180]
(Chrome version to duplicate this: Version 52.0.2743.116 (64-bit) on OS X)

![screen shot 2016-08-16 at 11 33 38 am](https://cloud.githubusercontent.com/assets/205007/17707351/a5063bb4-63a5-11e6-83f5-dd6e1a581ea9.png)

**Comment by reginafcompton** [comment]
This is done. Changed badge font size to a smaller percentage. Will push up this change in a new django-councilmatic version soon. 

font-size: 65%;
