### ISSUE TITLE
simple help text for email alerts for /about

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#182]
How often delivered? As they happen, as in RSS feed, right @mccc ? Or is there a default daily reminder email. As they happen is better, we think. 

cc @cathydeng just for her info. I'll take first draft of this, easy.

**Comment by mccc** [comment]
My goal during all of this is that everything _could_ happen as real-time as the scraper could handle (IMO the fact that we only scrape once a day limits the site's utility for hardcore users who are going to prefer a more up-to-date site), although one can also imagine users preferring daily emails. Those emails would probably have to be initiated by a separate cron job, though it could use the same notifications_email() redis queue to ultimately deliver them.

**Comment by reginafcompton** [comment]
I believe we have this taken care of, thanks to the new modal pop-ups, for example:

<img width="1258" alt="screen shot 2016-12-30 at 10 25 45 am" src="https://cloud.githubusercontent.com/assets/13078679/21568458/726a2450-ce7a-11e6-8721-253ccb9ab305.png">

Let me know if you need something more!

**Comment by reginafcompton** [comment]
Long over due for a closing.....
