### ISSUE TITLE
add "upcoming event" info to RSS for legislative items

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#183]
On a random [bill](https://nyc.councilmatic.org/legislation/t-2015-3518/) that has an upcoming event, subscribing to RSS feed for the bill shows one piece of history info, but not the upcoming event. 

(There is the "visit website" button right there, of course, which brings user to that date.) 

I'm wondering if it's worth it to include Upcoming event in the RSS feed itself? Because then it would be included in the email alert info as well? 

Totally feel free to make a call that the "visit website" button is fine, I'm not intense on this.) 

cc @cathydeng 

![intro_rss_view](https://cloud.githubusercontent.com/assets/116819/18527267/a54bac12-7a89-11e6-8952-e5baf539eea0.png)

**Comment by davidmooreppf** [comment]
Ha really not to lard up on enhancements, but if user research shows that users want to see individual legislative items in the "meeting" alerts, getting someone to add those could be a top priority feature. If that makes sense. I think upcoming meeting date, as above, is priority b/w these two.

**Comment by mccc** [comment]
Nah it makes sense to show upcoming events, I suspect this should be easy to add.

**Comment by brainwane** [comment]
I'd personally like upcoming events in a **calendar** feed (I've just submitted #225 for that), but until or instead of that, showing upcoming events in the RSS feed would be great.
