### ISSUE TITLE
on committee detail page, highlight next meeting event 

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#184]
E.g. on [education](https://nyc.councilmatic.org/committee/committee-on-education/), one could imagine an info box up top - as on homepage - with date of next meeting event. To see upcoming legislation on the event view itself. Just a wish list item, not priority.

**Comment by brainwane** [comment]
Hi! @davidmooreppf could you talk about why this issue is being closed? Is it because Councilmatic now does this, or because it's being dropped as a request?

**Comment by davidmooreppf** [comment]
Hi @brainwane - thanks for checking, appreciate the attention. I was actually just cleaning up the issues I opened here on DataMade's repo for the deprecated NYC version, I kept this open over on my repo for Councilmatic, seems like a good user-focused suggestion. We're interested in any volunteer contributions on the app, so folks reading can be in touch if they'd like to contribute a design for this info display.
