### ISSUE TITLE
check RSS feeds for committee events 

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#185]
On a given committee, say Education [detail page](https://nyc.councilmatic.org/committee/committee-on-education/), RSS feed next to meetings is invalid, showing w/ glitches. Same for Housing cmte, but Health cmte worked fine, so it's sporadic. Hunh. 

I'll help test this more thoroughly next week.

**Comment by reginafcompton** [comment]
@davidmooreppf 

Did you find other instances of this? I believe the RSS feeds are working well now....but let me know if you find other bugs.
