### ISSUE TITLE
display "alert" icon on all pages, even for not logged-in visitors

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#186]
Currently, alert megaphone only displays on [pages](https://nyc-staging.councilmatic.org/person/margaret-s-chin/) of trackable items when user is logged-in. 

Was hoping it would display throughout all visitor sessions, as the RSS feed does, and direct to /login. 

Do we have time for that switch? I should clarify, not needed at all this week, or even next. Maybe this will come next month. Looks great!

**Comment by cathydeng** [comment]
sure, that's an easy change

**Comment by reginafcompton** [comment]
This is done. This bullhorn displays for users not logged in, and when you click, it shows this:

<img width="633" alt="screen shot 2016-10-27 at 1 57 02 pm" src="https://cloud.githubusercontent.com/assets/13078679/19781085/5a12f896-9c4d-11e6-8406-87ae5fa8f5d5.png">

**Comment by fgregg** [comment]
Nice solution.
