### ISSUE TITLE
collect non-legistar info on council members?

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#19]
There are some interesting things we may want to collect for each council member that are not populated in Legistar, namely:
- Borough & Political Party - http://council.nyc.gov/html/members/members.shtml
- Caucus membership - http://council.nyc.gov/html/about/bla.shtml
- Links to website, etc?

If we're creating a back end to verify council members anyway, it might make sense to support this data. Someone would have to stay on top of updating it though.

**Comment by davidmooreppf** [comment]
Agreed, very very good to display that info on member profile pages. 

This is a task for me. Let me know what format you'd like this in here on GitHub - which member ID to peg each piece of info to, i.e. a template.

**Comment by derekeder** [comment]
@davidmooreppf cool - when we have an admin area for you to play around in, we'll add the fields to populate

**Comment by fgregg** [comment]
So, more info about politicians can be put into OCD
- Political party
- Websites
- Caucus Information

We can just write additional scrapers to get that info in.  (some of this
info can be stored in an `extras` field).

The info about borough isn't really about the council it's about the post.
I think we can associated an OCD division id to posts, but there doesn't
seem to be a way affiliating geographic details about the borders of the
division.

**Comment by derekeder** [comment]
good to know @fgregg. We should put as much into OCD as possible.

**Comment by derekeder** [comment]
@fgregg some of this stuff does look to be in Legistar, just not captured by the scraper:
- website 
- borough
- political party

<img width="1275" alt="screen shot 2015-08-24 at 4 03 01 pm" src="https://cloud.githubusercontent.com/assets/919583/9452466/ed9eb6ee-4a79-11e5-871a-e9df18a728ec.png">

Caucus info is not present.

**Comment by fgregg** [comment]
http://legistar.council.nyc.gov/MainBody.aspx Great catch!

**Comment by davidmooreppf** [comment]
I can get caucus info into the standard later - some are listed [here](http://council.nyc.gov/html/about/bla.shtml), plus the [Progressive Caucus](http://nycprogressives.com/) (which is Council leadership). I see there's also a [Republican](http://www.thirteen.org/metrofocus/2011/09/what-issues-should-the-city-council-take-up-this-session/) caucus & Co-op caucus, etc. So, not sure the comprehensive list, but can get it from the Speakers' office.

**Comment by fgregg** [comment]
As of https://github.com/opencivicdata/scrapers-us-municipal/commit/f797f95d9b1c43a97843f70e6354a072efda4d47 political parties and length of tenure are being scraped.

**Comment by fgregg** [comment]
OCD now has begin and end dates and party info

http://api.opencivicdata.org/ocd-person/df71d389-4bdf-431b-be56-078468512e4c/

**Comment by fgregg** [comment]
Also historic council members too.

**Comment by cathydeng** [comment]
replacing this w/ #51
