### ISSUE TITLE
new homepage featured bill for NYC Veterans Alliance

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#195]
Time to swap out Freelancers bill up top, and please insert new Details button link to our new featured intro ::  

https://nyc.councilmatic.org/legislation/int-1259-2016/

... w/ text, feel free to edit, current Freelancers text is 73 words and this is 138, so maybe it won't look good.  

On August 16th, the New York City Veterans Alliance introduced a bill to add uniformed service status as a protected class under NYC's non-discrimination statutes. The bill's primary sponsors are NYC Public Advocate Letitia James and council member Jumaane Williams, with two council co-sponsors. The legislation would also close a loophole by allowing NYC veteran property owners to take full advantage of the veteran property tax exemption. Nine veterans posted public comments of support on the NYC Councilmatic bill page - for example, "My husband and I were turned away from several apartments we applied to because the landlords were 'uncomfortable' with us using his VA disability payments as income."

The bill is currently referred to the Committee on Civil Rights, but is not currently scheduled for the committee's final hearing of the year on December 13th. 

--- 

Let's try attached photo, and if we prefer we can grab one from their public FB page :: 

https://www.facebook.com/NYCVeteransAlliance/photos/a.370115136512242.1073741828.366858876837868/584973818359705/?type=3&theater

(... the body camera bill can stay for now, might update it next week.) 

![nyc_veterans_alliance](https://cloud.githubusercontent.com/assets/116819/21030250/8baa8d76-bd6b-11e6-903d-2b1208ecc757.png)

**Comment by davidmooreppf** [comment]
Just a quick ping @reginafcompton that you saw this, seems permissions might have changed and I wasn't able to 'assign' it yesterday. Would be good to have on Monday the 12th, if you're able & around. Happy to chat.

**Comment by reginafcompton** [comment]
@davidmooreppf Got it! Will update this afternoon.
