### ISSUE TITLE
file issue for Civic Tech Issue Finder

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#2]
http://www.codeforamerica.org/geeks/civicissues

**Comment by fgregg** [comment]
What's this?

**Comment by davidmooreppf** [comment]
Forgot to self-assign. It's simply to have Councilmatic enhancements included here :: 

http://www.codeforamerica.org/geeks/civicissues. 

The US municipal scrapers could have an issue too, of course. @ondrae is point person for getting it listed.

**Comment by derekeder** [comment]
Don't think we need this.
