### ISSUE TITLE
email confirmation modal permenantly displaying

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#200]
when going to https://nyc.councilmatic.org/ and not logged in, this message displays:

<img width="1258" alt="screen shot 2017-01-17 at 2 48 58 pm" src="https://cloud.githubusercontent.com/assets/919583/22039245/2992bd02-dcc4-11e6-85e7-f9de4478e90e.png">

**Comment by derekeder** [comment]
this looks to be not showing anymore. not sure what fixed it.

**Comment by reginafcompton** [comment]
collectstatic!
