### ISSUE TITLE
alignment of account icon in upper-right menu bar, in Chrome

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#201]
Looks like upper-right "account person" icon isn't aligned correctly. 

This is logged-in to my user account, in Chrome. 

Logged-in in Safari seems fine, does not show the icon in orange and bumped-up. 

![screen shot 2017-01-17 at 3 55 50 pm](https://cloud.githubusercontent.com/assets/116819/22039469/7201c0ca-dccd-11e6-9fb0-883bd9a974d9.png)

![screen shot 2017-01-17 at 3 51 03 pm](https://cloud.githubusercontent.com/assets/116819/22039311/d05058f4-dccc-11e6-899c-adb922fd9472.png)

**Comment by reginafcompton** [comment]
Another job for collectstatic. 

@davidmooreppf, does this look correct, now?

**Comment by davidmooreppf** [comment]
Yep, looks correct now in Chrome. Feel free to close.
