### ISSUE TITLE
user comments gone in Disqus 

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#202]
E.g. on bottom of featured [bill page](https://nyc.councilmatic.org/legislation/int-1259-2016-a2a783b2419f/), where there had been nine or ten comments. Maybe the deploy nuked them? 

I can log in to our Disqus admin panel in a few minutes to see what comments are still there, to help see if we can restore.

**Comment by derekeder** [comment]
@davidmooreppf can you confirm the shortname for your Disqus account? Is it `nyc-councilmatic` or `nyccouncilmatic`?

**Comment by davidmooreppf** [comment]
It's nyc-councilmatic. Can hand off the login & pw to Admin over chat. #120 was a previous reference issue. I'll look more tmw but as of now, all the "Discussions" in Disqus admin say they were created five hours ago, so that would be the time of the deploy.

**Comment by davidmooreppf** [comment]
Picking this back up, I can start a Disqus support ticket to inquire about any way to access comments before last week's deploy. 

Realizing that Disqus is an add-on system, do we think the deploy fully re-installed Disqus too? It's not an emergency, but it would definitely be good to retrieve comments from Intro 1259, currently featured on homepage 

In Disqus Admin panel, previous user comments are not showing as "Deleted", they don't seem to appear anywhere. 

In Disqus Admin, there's a Discussions view that has ten legislative pages, somehow updated five hours ago, but there are no public comments on those pages, certainly not five hours ago today, so I don't know how Discussions is being defined. Can ask Disqus.

**Comment by davidmooreppf** [comment]
I'm gonna check in with Disqus this afternoon on this front, it's priority given some local media tmw. Just one last ping in case anything comes to mind on restoring from previous Disqus version. I'll dive in this afternoon though w/ Disqus support and maybe more documentation.

**Comment by reginafcompton** [comment]
Okay, David. When we last checked, it looked like comments were back...so, please let us know what Disqus has to say!

**Comment by davidmooreppf** [comment]
Disqus is there at bottom of pages, but ten user comments on [homepage legislative item](https://nyc.councilmatic.org/legislation/int-1259-2016-a2a783b2419f/) are still not on production.

**Comment by reginafcompton** [comment]
Ah, ok! I see. We'll look more closely at this.

**Comment by davidmooreppf** [comment]
OK, poked around Disqus admin more. I do need to get to bottom of this for our community group partner. 

Their help section didn't help. I started an [issue](https://disqus.com/home/channel/discussdisqus/discussion/channel-discussdisqus/admin_old_comments_from_all_not_moving_over_to_approved/) describing the below on their support forum. Gah. 

Under their /admin/moderate, old comments didn't appear under "pending" or "approved". 

But I went to "All" in "past year" and the old comments appeared. I saved a .txt dump just in case. But they wouldn't appear with their initial avatars unless we can restore them from below. 

So to try to make them appear, I went to one from last year on [intro 856](https://nyc.councilmatic.org/legislation/int-856-2015-98ac73760d75/), selected it, and clicked "approve". It saved as check-marked approved in same Disqus admin "all" comments view, but it's not on site, and not in "approved" section on Disqus admin. Attached image. 
![screen shot 2017-02-08 at 12 35 20 pm](https://cloud.githubusercontent.com/assets/116819/22749385/236f5c4e-edfb-11e6-9829-30034e15fb05.png)

So before I make any more checks in /admin, I'll stop here. You have the login for Disqus admin, yes? Can share. And we could screenshare for minute if that's more efficient. 

Misc notes: 

Is this how we embedded Disqus? [Universal code](https://nyc-councilmatic.disqus.com/admin/settings/universalcode/
)?


Anything happen in the notifications merge into Master that would have affected Disqus? I can't parse [files](https://github.com/datamade/nyc-councilmatic/pull/199/files) in detail.

**Comment by derekeder** [comment]
@davidmooreppf I looked into this and I believe I've figured out the cause. When we launched the new updates, we had to make some changes to the way we format the legislation URLs. This was put in place to handle potential conflicts where different legislation had the same URL. Here's an example:

* Old URL: https://nyc.councilmatic.org/legislation/int-405-2014/
* New URL: https://nyc.councilmatic.org/legislation/int-405-2014-e7a412d27734/

We have redirects setup to handle this, but it appears to be tripping up Disqus, as comments are associated to a specific URL. 

It looks like Disqus has some tools for migrating and moving comments for the exact scenario. David - do you want to try it out? https://help.disqus.com/customer/portal/articles/286778-migration-tools

**Comment by davidmooreppf** [comment]
Ah makes sense to me. I'll start that migration shortly. We have the same Disqus shortname so should merge OK...

I had seen page in Disqus help about importing comments from Drupal or WP or whatever, but hadn't seen that migration page.

**Comment by derekeder** [comment]
Great - let me know if it works and if you need anything from us.

**Comment by davidmooreppf** [comment]
So bottom of that page is a Redirect Crawler button. I can push it, but before I do, just confirming we have setup the 301 re-directs it's expecting to find? I mean, as opposed to something else? Ha just being cautious.

**Comment by derekeder** [comment]
@davidmooreppf yes, we have redirects set up for all the old URLs. Go for it!

**Comment by davidmooreppf** [comment]
I took the extremely technical step of pressing the button. They say it might take 24 hours, obvs. probably fewer since we have fewer re-directs. Will update.

**Comment by derekeder** [comment]
Woo. May we be blessed by the old gods and the new

**Comment by davidmooreppf** [comment]
So, here's my attempt to check on status. It could still be running but gives no such indication. 

The migration page said to check /admin/discussions [view](https://nyc-councilmatic.disqus.com/admin/discussions/) for updates. That view is showing ten discussion items (bit confusing), I think that's unchanged. It's definitely still just one page. 

But over on [Intro 856](https://nyc.councilmatic.org/legislation/int-856-2015-98ac73760d75/), the old comment I approved now appears. Though not in /admin/discussions. 

So I'm going to try approving an old comment on [Intro 1259](https://nyc.councilmatic.org/legislation/int-1259-2016-a2a783b2419f/) and seeing if it appears after I press the button again. If that works I'll replicate with all old comments.

**Comment by davidmooreppf** [comment]
Crawlers must have still been running b/c after posting this I hit refresh and nine comments re-appeared on homepage [Intro 1259](https://nyc.councilmatic.org/legislation/int-1259-2016-a2a783b2419f/), and seemingly on all other pages. 

So I don't really understand what /admin/discussions is showing, that had been confusing earlier as well when looking for old comments, but I think we're all set. 

I'll double check tmw and then close the issue. Thx Derek.

**Comment by reginafcompton** [comment]
This looks fixed. @davidmooreppf re-open the issue, if needed.
