### ISSUE TITLE
secure .csv dump of registered users

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#206]
No rush on this, not imperative for this week, just figured I'd start the ball rolling. 

Goal is to get me a simple .csv of registered users from the first week. However's secure works for me. 

I'm particularly wondering what happened to one user who I just tried to register in real time, a Civic Hall person named Jack Saul, as we couldn't find the confirmation email in his email app anywhere. No worries, I know this stuff happens of course, and I just tested on a ten-minute-email and it came through pretty quickly, so account registration is generally working. 

I have a private OpenGovernment repo that we use for encrypted communications to which I can add Regina or someone, for the .csv upload or paste.

**Comment by davidmooreppf** [comment]
This would be good to have by Thursday of this week, please, for ongoing outreach. I reckoned above was easiest, least time-intensive, but if it's easier to put it as a download in /account/subscriptions for my drm at ppolitics dot org email, that's fine. Probably not easier, ha.

**Comment by reginafcompton** [comment]
@davidmooreppf I sent you a message about this!
