### ISSUE TITLE
Login & user issue

### ISSUE THREAD

**Issue by tribzi** [datamade/nyc-councilmatic#207]
I cannot login at https://nyc.councilmatic.org/. When I click the user icon in the upper right it displays an email that isn't mine (sr218@hotmail.com). When I click logout it just refreshes the page. Clicking manage alerts gives me a 404.

It also does not allow me to login from https://nyc.councilmatic.org/login. When I try the password that I know is correct it tells me "Please enter a correct username and password. Note that both fields may be case-sensitive." The password recovery feature seems to work so I know the account was created successfully.

<img width="229" alt="screen shot 2017-01-24 at 11 50 01 pm" src="https://cloud.githubusercontent.com/assets/8650827/22278307/571507ea-e290-11e6-9406-60bb1794318c.png">

**Comment by davidmooreppf** [comment]
Thx for bug report - I'm noticing some glitches too. Primarily, logout isn't immediately responsive (on my main production site user account davidmooreppf). 

Last night I was testing acc't registration & login with a test email, and earlier this morning the blue-banner "Check your email for a link to confirm your account!" is persistent across browsers, even after I'm logged-in. But now that behavior seems to have stopped. 

I can help w/ trying to login/logout of davidmooreppf and askthemppf over chat if that's helpful later this afternoon.

**Comment by reginafcompton** [comment]
We'll look into this! Thanks.

**Comment by reginafcompton** [comment]
We have some issues with caching. We will turn-off caching temporarily, while we build out cache fragments for the templates. Thanks for bringing this to our attention!

**Comment by reginafcompton** [comment]
We've implemented partial caching to handle this! Explain in #208
