### ISSUE TITLE
checking on email digests

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#209]
At 10:12am ET this morning I got three emails from info @ councilmatic on my tracked items. No duplicate info, just happened to arrive in three separate emails. Just making a note in case we want to look at how those are compiled into one. Realize the data source can be unpredictable.

**Comment by davidmooreppf** [comment]
Two more emails at 11:12 am, all new info, non-duplicative. Maybe b/c I'm subscribed to "all events". But one of the 11:12 am emails does have a new bill sponsorship info in it. I can compile into a text file and email if helpful, or do a gist here.

**Comment by reginafcompton** [comment]
Yeah. We had to configure the Redis Queue on the server, so a lot of emails "waiting in line" were sent all at once this morning. So sorry about that! It should not be an issue again.

**Comment by davidmooreppf** [comment]
No problem, just in case it was something for the future.
