### ISSUE TITLE
double-check members' emails from official site

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#210]
I'll do this, piece of cake, just making a note. Some member emails aren't currently correct. 

@reginafcompton what format is easiest to get a simple spreadsheet of all 51 members? 

One column of: person/rosie-mendez-6aaf05a98863/ 

Second column of: email address?
 
Let me know what URL structure you'd like, e.g. the full URL.

**Comment by reginafcompton** [comment]
@davidmooreppf So...do you need us to make changes on the backend, and you'll be giving us a spreadsheet? (If so, the two columns you propose sounds good.)

Or do you want to make these changes using the Django admin view?

**Comment by davidmooreppf** [comment]
Yeah I had been wondering if there was a way for me to do it manually, but didn't see those emails in GitHub. So in Django /admin view, where to find them? Chat me anytime.

![screen shot 2017-02-13 at 9 57 36 am](https://cloud.githubusercontent.com/assets/116819/22888207/e60b8220-f1d2-11e6-82a8-9a694ced4f11.png)

**Comment by reginafcompton** [comment]
Okay....actually, this is something that needs to be changed on http://legistar.council.nyc.gov/.

**Comment by davidmooreppf** [comment]
Makes sense, as I didn't see our static pages for council member info. 

I'll work w/ council to fix it on Legistar. 

Before I close, is there no way we can do it on our end, if I made that spreadsheet? That's totally understandable, just triple checking. Not worth making it a big project.

**Comment by reginafcompton** [comment]
Unfortunately, no. We get that information from Legistar, so any updates will make in our database today would just be overwritten tomorrow, when we run our daily import data script.

**Comment by reginafcompton** [comment]
Ooopppss. I did not mean to close this.

**Comment by reginafcompton** [comment]
Let's keep the issue open, until you get things squared away with Legistar.

**Comment by davidmooreppf** [comment]
Cool I'll see how Council wants to fix it on Legistar [member pages](http://legistar.council.nyc.gov/PersonDetail.aspx?ID=34492&GUID=81BEA02C-AEC7-4B4B-AAED-E765FE87BF40&Search=).

**Comment by reginafcompton** [comment]
@davidmooreppf Did you get in touch with Council? do we still have email address problems? (In any case, whenever Legistar adds correct contact info, our scraper will grab it....so, closing this issue.)
