### ISSUE TITLE
Display individual bills for consideration on event detail page. 

### ISSUE THREAD

**Issue by reginafcompton** [datamade/nyc-councilmatic#213]
That is, grab the related_entities here: http://ocd.datamade.us/ocd-event/b3f49c6c-2489-4634-b27d-a4c021e5c754/

And display it here:

<img width="838" alt="screen shot 2017-02-18 at 7 19 19 pm" src="https://cloud.githubusercontent.com/assets/13078679/23098251/2fe158da-f60f-11e6-882d-e222ef8ca7dd.png">

**Comment by davidmooreppf** [comment]
That's great we have access to individual legislative items. This will be useful, whenever we can get to it.

**Comment by reginafcompton** [comment]
@davidmooreppf 

I added the relevant bills to the event detail page, e.g.: https://nyc-staging.councilmatic.org/event/committee-on-general-welfare-313052782cfd/

Is this what you had in mind? If so, I can put this on the production site.

**Comment by davidmooreppf** [comment]
How awesome! Looks perfecto. Will be happy to tout this at Personal Democracy Forum conference next week. Feel free to deploy at your convenience.
