### ISSUE TITLE
user login issue - report no registration email sent

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#216]
Just putting below from email into an issue. 

The admin shows that account - I didn't see a setting where I could "activate" or trigger another registration email, but of course as per below the user can reset pw. 

I just confirmed in a fresh browser that my davidmooreppf admin acc't login is working, as is my askthemppf non-admin acc't. 

---

On our end, it seems your account as below was created. 

Try signing-in first? 

https://nyc.councilmatic.org/signup/

… if that doesn't work, which it might not, try a password reset :: 

https://nyc.councilmatic.org/recover/

… and if that doesn’t work, simply let me know - we’ll either delete that account and you can register again. 

Thanks for using NYC Councilmatic! And let me know, please, we’ll get it fixed.

-David

On May 18, 2017, at 5:09 PM, Hashim Rahman <[DAVID REDACTED]> wrote:

Dear Councilmatic,

I signed up on your website for an account and received a message indicating that I should check email for confirmation.  I have not received any such email.  

Your assistance would be appreciated.  

user name: hrahman
email : DAVID REDACTED

**Comment by reginafcompton** [comment]
@davidmooreppf - sorry about the delay: we actually had to upgrade our email service to a monthly package, so that we can send more emails than was previously allotted. 

hrahman should have received an email. I also manually activated his account, so he can sign in without delay.
