### ISSUE TITLE
URL change for homepage featured bill

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#220]
Previously was linked from homepage, Vets bill: https://nyc.councilmatic.org/legislation/int-1259-2016-a2a783b2419f/ 

404's now. Intro is still findable from search :: https://nyc.councilmatic.org/legislation/int-1259-2016/

... but Disqus comments are gone again. I copied the content from previously, but guess should fix homepage link. I could edit it here in GH, but just mentioning it, I guess.

**Comment by reginafcompton** [comment]
Fixed!

**Comment by davidmooreppf** [comment]
I'll do the Disqus migrate tool process again in admin.

**Comment by davidmooreppf** [comment]
I'll just re-open this - I ran the migration tool in Disqus admin. Should take a day. 

My question is, was there a 301 re-direct set up from old link above to new link? 

That would be required: "If you've already set up 301 redirects for your site's pages, then use our Redirect Crawler to crawl your site's pages and migrate the URLs of your commenting threads automatically"

**Comment by davidmooreppf** [comment]
So migration tool didn't restore comments. 

Was the 301 redirect set up in this case? It might not have been.

**Comment by reginafcompton** [comment]
We did set-up redirection, but I'll look into why this bill does not get caught.

**Comment by davidmooreppf** [comment]
Just in case useful: https://help.disqus.com/customer/en/portal/articles/912834-redirect-crawler

**Comment by davidmooreppf** [comment]
Sorry to ping, I totally realize we don't have much bandwidth for fixes, but this is a priority for our community group partners here. Do we think 301 was in place? Should I run migration again in Disqus admin? That did work last time, pressing the button.

**Comment by davidmooreppf** [comment]
I should mention, I can access them both in Disqus admin and on a [public page](https://disqus.com/home/discussion/nyc-councilmatic/introduction_1259_2016_nyc_councilmatic/oldest/), so they're not lost, but having them display on the production site as soon as possible is still preferable for their advocacy.

**Comment by reginafcompton** [comment]
I revised the redirect, and it's behaving as expected on the Councilmatic side.

**Comment by davidmooreppf** [comment]
Pressed the button again in Disqus-admin to migrate, will see if it catches this time. Thx.

**Comment by davidmooreppf** [comment]
Ah, they're back. All set, thx.
