### ISSUE TITLE
private demo site for Thursday Aug. 27th

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#23]
As @derekeder & I briefly discussed last Friday - on 8-27 at 2pm ET, I have a meeting for a private demo of NYC site. 

So that morning, goal is to have a pw-protected version up somewhere for me to show in whatever shape it's in. Heroku or staging site or whatever is fine, or NYCCouncilmatic.org if you want that. 

This preview does not need to be mailed out to Council offices yet, so any URL is fine, maybe just one admin login / pw for us. Nothing complicated. 

Emailing a bit more info on what data to load, and feature priorities to demo. Flexible.

**Comment by derekeder** [comment]
done!
