### ISSUE TITLE
typology of committee actions

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#25]
Here's all the possible actions a committee has taken on a bill. We should establish a topology for these actions and indicate which ones are positive vs negative as far as progressing the legislation

Hearing Held by Committee
Introduced by Council
Referred to Comm by Council
Approved, by Council
Approved by Committee
Laid Over by Committee
Filed, by Committee
Amendment Proposed by Comm
Hearing on P-C Item by Comm
Approved by Committee with Companion Resolution
Approved by Council
Amended by Committee
Sent to Mayor by Council
Approved by Subcommittee
P-C Item Approved by Comm
Signed Into Law by Mayor
Recved from Mayor by Council
Hearing Held by Mayor
Approved by Committee with Modifications and Referred to CPC
Laid Over by Subcommittee
P-C Item Approved by Committee with Companion Resolution
Recessed
Filed by Council
Filed by Committee
Approved with Modifications and Referred to the City Planning Commission pursuant to Rule 11.70(b) of the Rules of the Council and Section 197-(d) of the New York City Charter.
Approved by Subcommittee with Modifications and Referred to CPC
P-C Item Laid Over by Comm
Rcvd, Ord, Prnt, Fld by Council
City Charter Rule Adopted
P-C Item Approved by Subcommittee with Companion Resolution
Hearing Scheduled by Mayor
Filed by Committee with Companion Resolution
Filed by Subcommittee
Withdrawn by Mayor
Re-referred to Committee by Council
Laid Over by Council

**Comment by fgregg** [comment]
You can reuse some mapping work I did here: https://github.com/datamade/municipal-scrapers-us/blob/master/nyc/bills.py#L153-L189

**Comment by derekeder** [comment]
@fgregg nice - this is perfect

**Comment by fgregg** [comment]
Note that those mapped values are available through the API.

**Comment by derekeder** [comment]
done via 6c21141a4685d67cb5aff26bf15e439dc2130e5c
