### ISSUE TITLE
committee descriptions

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#26]
Collect and display a description for each committee.

Info is contained in this PDF: http://legistar.council.nyc.gov/View.ashx?M=AO&ID=22897&GUID=f5467935-ab1e-4467-aba5-fb15ae592837&N=RGVzY3JpcHRpb25zIGFuZCBKdXJpc2RpY3Rpb25zIG9mIENvbW1pdHRlZXM%3d

---

The standing committees of the Council shall bear the following titles and possess the following substantive matter jurisdictions:
AGING - Department for the Aging and all federal, state and municipal programs pertinent to senior citizens.
CIVIL RIGHTS – Human Rights Commission, Equal Employment Practices Commission and Equal Employment Opportunity.
CIVIL SERVICE AND LABOR - Municipal Officers and Employees, Office of Labor Relations, Office of Collective Bargaining, Office of Labor Services, and Municipal Pension and Retirement Systems.
COMMUNITY DEVELOPMENT - Issues relating to poverty and its reduction especially in low income neighborhoods.
CONSUMER AFFAIRS - Department of Consumer Affairs.
CONTRACTS - Procurement Policy Board, review of City procurement policies and procedures, oversight over government contracts, Mayor's Office of Contract Services and collection agency contracts.
COURTS AND LEGAL SERVICES - Courts and Legal Aid.
CULTURAL AFFAIRS, LIBRARIES AND INTERNATIONAL INTERGROUP RELATIONS - Department of Cultural Affairs, libraries, museums, Art Commission, New York City Commission for the United Nations, Consular Corps and Protocol, Mayor’s Office of Special Projects and Community Events, and to encourage harmony among the citizens of New York City, to promote the image of New York City and enhance the relationship of its citizens with the international community.
ECONOMIC DEVELOPMENT - Economic Development Corporation and Department of Small Business Services.
EDUCATION – Department of Education, School Construction Authority and charter schools.
ENVIRONMENTAL PROTECTION - Department of Environmental Protection and Office of Long Term Planning and Sustainability.
FINANCE - Executive Budget review and Budget modification, Banking Commission, Comptroller's Office, Department of Design and Construction, Department of Finance, Independent Budget Office and fiscal policy and revenue from any source.
￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼
FIRE AND CRIMINAL JUSTICE SERVICES - Fire/EMS (non-health-related issues), Department of Probation, Department of Correction, and Emergency Management Department (OEM).
GENERAL WELFARE - Human Resources Administration/Department of Social Services, Administration for Children's Services, Department of Homeless Services, Office of Immigrant Affairs and charitable institutions.
GOVERNMENTAL OPERATIONS - Municipal governmental structure and organization, Department of Citywide Administrative Services, Community Boards, Tax Commission, Board of Standards and Appeals, Campaign Finance Board, Board of Elections, Voter Assistance Commission, Commission on Public Information and Communication, Department of Records and Information Services, Financial Information Services Agency and Law Department.
HEALTH - Department of Health and Mental Hygiene, Health and Hospitals Corporation and Office of the Chief Medical Examiner and EMS (health-related issues).
HIGHER EDUCATION - City University of New York.
HOUSING AND BUILDINGS - Department of Housing Preservation and
Development, Department of Buildings and rent regulation.
IMMIGRATION - Mayor’s Office of Immigrant Affairs and other matters affecting immigration.
JUVENILE JUSTICE – Division of Youth and Family Justice within the Administration for Children’s Services.
LAND USE - City Planning Commission, Department of City Planning, Department of Information Technology and Telecommunications, Landmarks Preservation Commission, land use and landmarks review.
MENTAL HEALTH, DEVELOPMENTAL DISABILITY, ALCOHOLISM, SUBSTANCE ABUSE AND DISABILITY SERVICES - Department of Health and Mental Hygiene (issues of mental health, developmental disability and alcoholism services) and Mayor’s Office for People with Disabilities.
OVERSIGHT AND INVESTIGATIONS - To investigate any matters within the jurisdiction of the Council relating to property, affairs, or government of New York City and the Department of Investigation.
PARKS AND RECREATION - Department of Parks and Recreation. PUBLIC HOUSING - NYC Housing Authority.
￼￼￼￼￼￼￼￼￼￼￼￼￼￼
PUBLIC SAFETY - Police Department, District Attorneys, Special Narcotics Prosecutor, Civilian Complaint Review Board, and Criminal Justice Coordinator.
RECOVERY AND RESILIENCY – Office of Recovery and Resiliency, issues relating to recovery in Hurricane Sandy-affected communities, including the Build It Back Program, and the Office of Long Term Planning and Sustainability as it relates to efforts to make New York City more resilient in the face of climate change, and preparing for, responding to, and recovering from emergencies.
RULES, PRIVILEGES AND ELECTIONS - Council structure and organization and appointments.
SANITATION AND SOLID WASTE MANAGEMENT - Department of Sanitation and the Business Integrity Commission.
SMALL BUSINESS - Matters relating to retail business and emerging industries. STANDARDS AND ETHICS - Conflicts of Interest Board and Council Ethics.
STATE AND FEDERAL LEGISLATION - Federal legislation, State legislation and Home Rule requests.
TECHNOLOGY – Technology in New York City, Department of Information Technology and Telecommunications (non-land use-related issues), Mayor’s Office of Media & Entertainment, NYC TV and dissemination of public information through the use of technology.
TRANSPORTATION - Mass Transportation Agencies and facilities, Department of Transportation, New York City Transit Authority and Taxi and Limousine Commission.
VETERANS - Mayor’s Office of Veterans Affairs and other veteran related issues. WATERFRONTS - Matters relating to the waterfront.
WOMEN'S ISSUES - Issues relating to public policy concerns of women, domestic violence, Office to Combat Domestic Violence and Agency for Child Development.
YOUTH SERVICES - Youth Board, Department of Youth and Community Development, Interagency Coordinating Council on Youth, and youth related programs.

**Comment by cathydeng** [comment]
I'll add this to the city config in the app, similar to #30
