### ISSUE TITLE
preserve order of actions that happen on same day

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#27]
Often times, multiple actions will be taken on a piece of legislation on the same day. However, we are sorting by date of action for the front-end, so the actions display out of order in some cases:

<img width="666" alt="screen shot 2015-08-24 at 10 30 46 pm" src="https://cloud.githubusercontent.com/assets/919583/9458080/ccbf1168-4aaf-11e5-944d-372eeaa7061a.png">

<img width="678" alt="screen shot 2015-08-24 at 10 31 29 pm" src="https://cloud.githubusercontent.com/assets/919583/9458085/e0b7af18-4aaf-11e5-8e2a-217ca5b5502d.png">

**Comment by derekeder** [comment]
This also affects the `current_org` property, as its determined by the last action taken.

**Comment by fgregg** [comment]
The actions in the json array should be in the reverse chronological order (newest first).

**Comment by cathydeng** [comment]
closed via 03f7e0b496691d82bb914e7e3402ec3b8ab164e6, now all actions can be sorted by `order`
