### ISSUE TITLE
display friendlier bill labels

### ISSUE THREAD

**Issue by cathydeng** [datamade/nyc-councilmatic#29]
bill labels have redundant info b/c we are also showing the org. let's make more readable labels by removing 'by X'

<img width="727" alt="screen shot 2015-08-25 at 5 15 32 pm" src="https://cloud.githubusercontent.com/assets/1406537/9481112/2c8f2d92-4b4d-11e5-9a56-63dc57d0fec5.png">

**Comment by derekeder** [comment]
Good observation. In the case that a bill is currently in a committee (ie not city council or the mayor) i think its valuable to display this. Let's add some customization for displaying this.
