### ISSUE TITLE
display of public meeting agendas

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#3]
Goal is to support display of agendas and minutes from [events](http://docs.opencivicdata.org/en/latest/api/search.html#event-search). First pass, of course, was on [AskThem Philly](http://www.askthem.io/pa-philadelphia/overview/meetings), but here for NYC Councilmatic. 

Simplest seems to be adding a top menu item for Events, and then displaying them in a list as with [legislative objects](http://chicagocouncilmatic.org/legislation/2362076). Agendas & minutes could go in body, where Descriptions & Actions are now, or whatever. 

Enhancement we considered on old OpenGovernment: DocumentCloud display of .pdf's 

Another enhancement is UI & design ideas - or re-using - [MuniciPal] UI (http://municipal.mesaaz.gov/) - the view of calendar dates, etc., is actually hard to pull up right now. Maybe council is out of session, addresses just go to members' profile pages. Anyway.

**Comment by derekeder** [comment]
We can shoot for adding events to the council and committee pages, along with associated documents.

This info is already being scraped and imported into OCD: http://api.opencivicdata.org/events/?jurisdiction_id=ocd-jurisdiction/country:us/state:ny/place:new_york/government
