### ISSUE TITLE
bill type descriptions

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#30]
Path to Mayor - & planning cmte. 

Letter from Mayor

**Comment by derekeder** [comment]
Here's the full list of legislation types, ordered by frequency (most common at the top). We should have a definition for each:

Introduction
Resolution
Oversight
Land Use Application
Communication
Land Use Call-Up
Mayor's Message
SLR
Tour
Local Laws 2015
Petition

**Comment by davidmooreppf** [comment]
Excellent, will raise with Council to determine a process for this after next meeting.

**Comment by davidmooreppf** [comment]
Copy below is from Council staff - figuring out now how to attribute it. 

The below could go on its own /about page, e.g. /about/NYCCouncil, but let's chat over the domain. 

So the "Introduction" part below explains the bill-to-law process, and the other definitions could be used in hover-overs, if you like- whatever you have planned. 

NYC Council Speaker's staff will be producing more "libre" content on How Council Works, primarily for their official site, which we can use at a later date. But prob. doesn't exist before our beta launch. 

---

Introduction:   Council makes and passes the laws governing the city. Legislation pending in the Council is called an Introduction.   When an Introduction is passed by the Council and adopted in one of the 3 ways described below it becomes a Local Law and is given a Local Law number.

Once the Introduction is approved by the Council it is sent to the Mayor who holds a public hearing on it.  Once it is signed by the Mayor it becomes a Local Law.

If the Mayor disapproves and vetoes the Introduction, the bill comes back to the Council with the Mayor’s written objections (Veto Message).   The Council at a subsequent meeting held within 30 days can override the Mayor’s veto by a two-thirds vote.  

If the Mayor chooses not to sign or veto a bill within a prescribed thirty-day time period, the introduction becomes a local law and is enacted pursuant to the City Charter due to the lack of Mayoral action.

Resolution:  Resolutions are used by the Council as a vehicle for legislative action and to express the sentiment of the body on important public policy issues. These issues may or may not fall under City jurisdiction.  Resolutions are often used to support federal or state legislation, commemorate people and historical dates, or even criticize or denounce practices and policies.  Resolutions are also mechanisms in which the Council adopts the budget and land use items.

Oversight:   A hearing held with respect to an oversight topic not on a specific piece of legislation.

Land Use Application:  Each application or submission that is to be considered by the Council’s Land Use Committee

Communications: Communications sent by city, county and borough offices to the Council for consideration.  These include requests for advice and consent on appointments to various boards and commissions.

Land Use Call-Up:  Land use items that do not require Council approval to be enacted but have been chosen by any given Council Member for discretionary review by the Council. 

Mayor’s Messages:  Messages and Papers from the Mayor include Mayoral Home Rules Requests, requests for advice and consent on appointments to various City commissions and boards, and veto messages. 

SLR (State Legislation Resolution):  A special resolution that serves as an official home rule request from the Council to the State Senate and State Assembly to pass pending legislation in the New York State Legislature.  The initial request for a SLR must come from the Legislature in Albany.

Tour:   A brief fact-finding trip taken by members of a respective committee in order to view or inspect a place or site that has relevance to their committee’s jurisdiction.  It is considered an official meeting of a Committee.

Local Law 2015:    All local laws that have been enacted for the year 2015.

Petitions/Communications - Communication originating from individuals or entities other than the Mayor, City, County and Borough Offices.  These generally include communications from the Council, such as Council appointments and resignations.

**Comment by cathydeng** [comment]
these have been added to the about page. the language here is a little wordy/complex - I'll go in and make em more concise
