### ISSUE TITLE
search: index people & events

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#32]
From /search, a member's last name, e.g [Lander](http://nyc-councilmatic.datamade.us/search/?q=lander), doesn't pull up a link to Lander's [profile page](http://nyc-councilmatic.datamade.us/person/brad-s-lander). 

What's possible here, in terms of adding the members' names and displaying them up top in their own section on searches for those terms? Maybe this is linked to sponsor search issue you mentioned. 

Similar question for committee names, e.g. [Housing](http://nyc-councilmatic.datamade.us/search/?q=housing) doesn't yet link to [Housing Cmte](http://nyc-councilmatic.datamade.us/committee-detail/committee-on-housing-and-buildings/) page.

**Comment by derekeder** [comment]
@davidmooreppf ah so we built the search page to be for searching just legislation. Committees and Council Members are not indexed. Instead, we are treating them as facets to filter legislation.

**Comment by davidmooreppf** [comment]
OK - I'll write a separate issue for the process of adding them to search corpus, as I'm fairly certain visitors will want to find their members or issue-areas by searching on homepage, etc. 

For now, let's tweak the gray help text in the search bar to make it clear it's just for legislation - currently it has a name and committee in it, de Blasio etc.- and write the help text in line with whatever's in search corpus, as in #34.

**Comment by derekeder** [comment]
We have the ability to find council members in a better way now: https://nyc.councilmatic.org/council-members/

Also 'search' has been renamed to legislation, so there's less room for confusion here
