### ISSUE TITLE
"verified" design on member's profile page

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#33]
For Thursday, having the "verified" design elements also display on Speakers' [profile page](http://nyc-councilmatic.datamade.us/person/melissa-mark-viverito/) would be great. That's in addition to the [members](http://nyc-councilmatic.datamade.us/council-members/) list view. I think this is in the works.

**Comment by derekeder** [comment]
implemented in be662edfde449ac93d81279b1a79dfb6abd4de1c, though not deployed yet.
