### ISSUE TITLE
search including intros from 2014? 

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#34]
Is search only displaying 2015 legislation? Should have 2014, too, as that was the first year of this council session. 

E.g., chokehold bill is intro 540 of 2014 - [searching 540](http://nyc-councilmatic.datamade.us/search/?q=540) only pulls up the 2015 bill, ideally should offer [2014 one](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2015556&GUID=1CB2BD89-B975-4B62-B225-1ACDA495C354&Options=ID|Text|&Search=540).

**Comment by derekeder** [comment]
We're only scraping 2015 bills at this point. @fgregg can we flip that switch to pull 2014 as well?

**Comment by fgregg** [comment]
Fixed with https://github.com/opencivicdata/scrapers-us-municipal/commit/f797f95d9b1c43a97843f70e6354a072efda4d47

**Comment by fgregg** [comment]
This is now on the serrver. Ready for you refresh.

**Comment by cathydeng** [comment]
we now have data from Jan 2014 onwards
