### ISSUE TITLE
display Name & Title & Summary on legislation detail page

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#35]
Realize you're working on this today. Relates to #17.

For example, on Intro [877](http://nyc-councilmatic.datamade.us/bill-detail/int-877-2015/), goal is to display info from [official page](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2404423&GUID=240D161E-E848-46BE-94D4-C886FFD1F970&Options=ID|Text|&Search=877).

**Comment by derekeder** [comment]
@davidmooreppf name is now showing up that was a bug. Summary seems a bit redundant with Name, so we're leaving it out.
