### ISSUE TITLE
display Summary from full legislation text

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#40]
Late-breaking enhancement here, re: #17. 

On bill text pages, most intros this session (need to double-check this) have a plain-language summary atop the [text page](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2103584&GUID=632A9A91-7FD5-424A-880D-7A4E0A8AD0B2&Options=ID|Text|&Search=607) - part of the Council's rules reform. 
- goal is to display that on leg. item pages, below the Title. Here's [607 of 2015](http://nyc-councilmatic.datamade.us/legislation/res-607-2015/), different bill, just to have handy.

**Comment by cathydeng** [comment]
we now have the summaries in the ocd api under `abstract`. I can add this to the bill pages.
