### ISSUE TITLE
inferring legislation status - stale legislation

### ISSUE THREAD

**Issue by cathydeng** [datamade/nyc-councilmatic#43]
there's a lot of legislation that was introduced & referred to a committee months ago, but then nothing happens. after what period of time, approximately, can we mark legislation w/ a label indicating that it looks stale? would the period of time vary for different types of legislation?

related to #28

**Comment by fgregg** [comment]
Can you do a little analysis of the time between referral and next action for legislation that has a next action. A simple histogram might show something like  99% of leg that move past refererrals happen within 28 days or something like that.

Paging @jernsthausen

**Comment by cathydeng** [comment]
done - now legislation is considered stale if the last action was over 60 days ago b/c ~80% of legislation that moves past referrals has its next action within 2 months

**Comment by davidmooreppf** [comment]
Thrilled, thanks @cathydeng & team.
