### ISSUE TITLE
simple login & pw on demo site

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#44]
For my previews next week, think it's helpful if we put up a simple pw, so people know it's not to be shared on social media yet. 

Our opsec is so secure I'll even suggest here in plaintext: login: nyc, pw: councilmatic. 

This issue will only become more & more intensively technical from here on out. I can do wireframes if helpful and bring in some consultants.

**Comment by davidmooreppf** [comment]
Thx @cathydeng - but is demo site working for you? Erroring for me now: TemplateDoesNotExist at /. Or maybe it's another temp issue.

**Comment by cathydeng** [comment]
yup http://nyc-councilmatic.datamade.us/ is working for me - you might have caught it just as I was updating

**Comment by davidmooreppf** [comment]
Ha all good.

**Comment by davidmooreppf** [comment]
So homepage is protected w/ login, but pages such as /search are reachable w/out login & pw, and got linked on Twitter after T-Camp. No big deal, just wondering if that's easy to change. Not worried about it much.

**Comment by cathydeng** [comment]
kk, updated the live site so that all pages require login
