### ISSUE TITLE
Google Analytics is out of date

### ISSUE THREAD

**Issue by konklone** [datamade/nyc-councilmatic#46]
The GA script is using the old non-Universal Google Analytics code. It's worth upgrading to Universal Analytics:

https://developers.google.com/analytics/devguides/collection/upgrade/?hl=en

**Comment by derekeder** [comment]
upgraded our Google Analytics library to super Universal Analytics: https://github.com/datamade/google-analytics-lib

**Comment by akuckartz** [comment]
Why not Matomo (fka Piwik) ?
