### ISSUE TITLE
finalize home page content

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#49]
Right now we're just showing the most recent legislation. Pretty meh.

Things we could show:
- upcoming events
- recently passed
- recently introduced
- @davidmooreppf picks a set of bills to feature
- some kind of category browser (this would require a way of categorizing every bill)

**Comment by davidmooreppf** [comment]
Yeah, in my private issue I had previously suggested an issue area gallery - but that would require a bit more development time, for me to be able to set 12-24 bills editorially, linked from, say, the "public housing" icon. We can wait on that. 

I think I'd lean towards a set of bills to feature - those from verified offices, probably. I think two bills would be fine, below search field. This highlights our public comment program. 

Then below that maybe upcoming events, if doing the view for that isn't too gnarly. 

"Recent legislation" seems like a helpful indicator that this is a timely-refreshed site with every item of legislation, but that could also be a line of copy. 

I can snap a photo of a drawing.

**Comment by derekeder** [comment]
Let's shoot for:
- [x] next city council meeting
- [x] next 3 events
- [x] recently passed bills
- [x] hard code 2-3 featured bills with contextual descriptions

**Comment by cathydeng** [comment]
closed via cec421140d27954abb5741de58ef98a9565e62f6
