### ISSUE TITLE
identify what committee a bill was sent to

### ISSUE THREAD

**Issue by cathydeng** [datamade/nyc-councilmatic#5]
in the ocd api, when bills get referred to committees, the action only captures the organization where the action came from (ny city council).

we need to capture what org is currently responsible for a piece of legislation, in addition to what org performed the last action.

example:
http://api.opencivicdata.org/ocd-bill/002c3999-1986-4de8-b709-d9c3a552367e/
http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2240474&GUID=55EA0398-F97F-49D2-A3CB-6223C525A141

**Comment by fgregg** [comment]
This is a tricky one.

**Comment by fgregg** [comment]
This describes the first thing that has to happen is to make a PR to imago. See https://github.com/opencivicdata/scrapers-us-municipal/issues/46

**Comment by fgregg** [comment]
This depends on the merging of https://github.com/opencivicdata/pupa/pull/195

**Comment by fgregg** [comment]
So, we are capturing this, but it has not yet been exposed on the OCD API endpoint: https://github.com/opencivicdata/imago/pull/62

**Comment by fgregg** [comment]
Okay, this is done now. See http://api.opencivicdata.org/ocd-bill/000ed562-4c43-4b1e-b6ee-2c9d13f6f273/

Look at the 'related entities' for the action 'committee-referral'
