### ISSUE TITLE
what's up w/ local laws?

### ISSUE THREAD

**Issue by cathydeng** [datamade/nyc-councilmatic#52]
it looks like all local laws for a year are published as one piece of legislation on legistar, with a bunch of attachments, one for each individual local law. why?

[the only councilmatic search result where legislation type is local law](http://nyc-councilmatic.datamade.us/legislation/t-2015-3094/)
[the corresponding page on legistar](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2328524&GUID=E0B4EE30-B5F7-4E90-9C97-CF96D5385E01)

how should we deal with storing/displaying local laws?

**Comment by fgregg** [comment]
attn @davidmooreppf

**Comment by cathydeng** [comment]
should we hide local laws on the site? it's kind of confusing, because it doesn't look like it has any additional info over the original passed introduction, & lacks history & is all condensed into one per year

**Comment by fgregg** [comment]
:+1

On Mon, Sep 28, 2015 at 10:25 AM, Cathy Deng notifications@github.com
wrote:

> should we hide local laws on the site? it's kind of confusing, because it
> doesn't look like it has any additional info over the original passed
> introduction, & lacks history & is all condensed into one per year
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/52#issuecomment-143776758
> .

## 

773.888.2718

**Comment by davidmooreppf** [comment]
Let's keep it - sorry I haven't gotten the legislative explanation yet, will do this week. At least it directs visitors to the Attachments tab.

**Comment by cathydeng** [comment]
for clarity, can we just put a link to all local laws on the about page, when describing introductions?

**Comment by davidmooreppf** [comment]
That's fine with me, but why is it misleading to keep it under the Filter Results menu, even with the "one" next to it, and have the visitor click over to Attachments? But we can take another crack at this as we enhance the explainers.

**Comment by cathydeng** [comment]
I think it's misleading/confusing to treat local laws as a distinct bill type, when really it is an introduction that has been passed. It also doesn't really fit into the data model for legislation, since it doesn't have sponsors or action history

I'll add a link to all the local laws from the about page - putting that together now!
