### ISSUE TITLE
about: overview of how City Council works

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-councilmatic#53]
add a friendly description of how NYC City Council works. We should also write something friendly for the home page #49

**Comment by davidmooreppf** [comment]
Rushed this basic overview - edits welcome. Thinking placement of below sentence just above or below search bar, whichever looks better. 

The NYC Council is composed of 51 members, in 39 committees and 7 subcommittees, making and passing the laws that govern the city. How Council works (/about/council). 

---

/about/council copy 

The Council monitors the operation and performance of city agencies, makes land use decisions and has sole responsibility for approving the city's budget. It also legislates on a wide range of other subjects. The Council is an equal partner with the Mayor in the governing of New York City.

Most of the Council's legislative work is done in committee. It is there that proposed legislation is initially debated and the members of other government branches and the public are given a chance to comment. 

Each committee has one Chairperson and an average of seven members, meeting in public hearings at least once per month, usually two or three times per month. 

Legislation pending in the Council is called an Introduction. When an Introduction is passed by the Council and adopted in one of the 3 ways described below, it becomes a Local Law and is given a Local Law number for that calendar year (e.g., Local Law 11 of 2011). 

Most Council hearings are held in the Council Chambers or the adjoining Committee Room in City Hall. Hearings are also held in the Hearing Room on the 16th Floor of 250 Broadway. Meetings of the entire Council, referred to as Stated Meetings, are held twice a month at City Hall.

Council members generally serve four year terms - the current 2014-2017 class was elected on Nov. 5th, 2013, and the next election will be on November 7th, 2017. 

For more info, see official [About NYC Council page](http://council.nyc.gov/html/about/about.shtml) or [Wikipedia page](https://en.wikipedia.org/wiki/New_York_City_Council), and email david@ppolitics.org with questions. 

---

Then the legislative term definitions from #30, already on About page on preview site. 

Could use following research for probability / insights/ context: 

How many local laws does a cmte. pass per month, or year or session. 

How many local laws were sponsored by Speaker and percentage. 

How many local laws were sponsored as Intros by committee chair. 

How many Mayoral vetoes in past recent councils, and how many of those have been overridden. 

How many local laws passed with at least one cosponsor from opposite party. 

What percentage of Intros pass into Local Laws, with what key shared features (out of committees with more members?, etc.). 

Will keep researching this, this was on my plate.

**Comment by davidmooreppf** [comment]
cc'ing @cathydeng. Gotta jump offline for a bit, back online 7pm eT.

**Comment by cathydeng** [comment]
**proposed edits plus some notes/questions:**

The New York City Council has 51 council seats, with each representative typically serving a four year term. The current legislative session runs from 2014 to 2017, and the next local election will take place on November 7th, 2017.

The Council is an equal partner with the Mayor in governing New York City. Its responsibilities include:
- approving local legislation
- monitoring the performance of city agencies _[@davidmooreppf is this in the data we have, to tie to website content? if so, what's the bill type?]_
- making land use decisions
- approving the city's budget _[@davidmooreppf is this in the data we have, to tie to website content? if so, what's the bill type?]_

Legislation that's pending in the Council is called an Introduction. When an Introduction is passed, it becomes a Local Law. _[we should add some more context here & tie it to the content on the site - e.g. 'you can see that city council does a lot of X Y Z, but the most interesting stuff is introductions b/c those are baby laws' (but worded better)]_

Most of the Council's legislative action happens in committees. Each committee meets in public hearings 2-3 per month. There, proposed legislation is debated and members of other government branches, as well as the public, are able to comment.

Meetings of the entire Council, referred to as Stated Meetings, occur twice a month at City Hall. _[@davidmooreppf can we add a sentence or two elaborating on stated meetings? are they also open to the public? what goes on? how is it diff from committee meetings?]_

**Comment by cathydeng** [comment]
@davidmooreppf some questions:
- how does city council monitor the performance of city agencies? what's the bill type?
- does approving the city's budget happen via resolutions?
- should we also add 'express opinion on public policy outside of NYC' under city council responsibilities, b/c of resolutions & SLRs?
- what happens are stated meetings & how are they diff from committee meetings?

**Comment by davidmooreppf** [comment]
Finally getting these to Council now. Will try to get info on Stated Meetings quickly.
