### ISSUE TITLE
access to domain: NYCCouncilmatic.org

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#54]
Howdy @rcheklauk, meet Derek & team, tech leads for NYC Councilmatic. Goal is to get our new Councilmatic site set up at our domain nyccouncilmatic.org (.com, etc.) - as this entails less work now than nyc.councilmatic.org, which will come next. 

Currently nyccouncilmatic.org is on AskThem server setup, n'est-ce pas? Please link up with derek,eder at the popular Gmail service to give him full access. (Emailing this to Rob now.)

**Comment by rchekaluk** [comment]
Note from @derekeder 

> We don't need to commission a new server, though. We've got one setup already. All we really need is access to the DNS config.
> 
> Or, if someone wants to make the change themselves all we need to do is update the 'A' record for nyccouncilmatic.org to point to 52.21.185.73.

**Comment by rchekaluk** [comment]
DNS changed to 52.21.185.73 for:
- nyccouncilmatic.co
- nyccouncilmatic.com
- nyccouncilmatic.net
- nyccouncilmatic.org

DNS also changed (let me know if incorrect) to 52.21.185.73 for:
- councilmatic.org

**Comment by derekeder** [comment]
Great - http://nyccouncilmatic.com is now live! Password wall is still up.

For the other nyccouncilmatic domains, can we have them all do a DNS redirect to nyccouncilmatic.com?

For councilmatic.org I'm not sure we should have changed it. That site is still being maintained by @mjumbewu I think.

**Comment by davidmooreppf** [comment]
Ah - I'd like nyccouncilmatic.com to diret to nyccouncilmatic.org. I'd like the .org to be the site. 

Derek I'll ping you in a sec to see about what to do about councilmatic.org. Just setting up.

**Comment by derekeder** [comment]
@davidmooreppf ah ok. in that case, lets set up all the nyccouncilmatic.**\* domains to point to .org. We'll make the necessary changes on our end.

**Comment by davidmooreppf** [comment]
Sorry @mjumbewu - filed an issue for @rchekaluk to point it back to previous, didn't mean to flip that one.

**Comment by davidmooreppf** [comment]
New approach, friends, let's chat over what's feasible here. 

@rchekaluk please hand over DNS keys for Councilmatic.org to Derek? He'll carve out time for our splash page linking to our three cities and more to come. Rob might not have time to do this until after work ET, not sure... 

@mjumbewu sorry this got rushed a bit - how can we re-direct your current Philly Councilmatic site to another domain? You can coordinate w/ @derekeder on whatever's easiest, I'm agnostic as to philadelphia.councilmatic.org or another domain on DataMade's side.

**Comment by rchekaluk** [comment]
@derekeder FYI the "councilmatic" domains are split between different registrars, see:
- https://github.com/opengovernment/ops/wiki/Sysadmin-Notes#systemwide-domains
- https://github.com/opengovernment/ops/wiki/Sysadmin-Notes#systemwide-dns

**Comment by rchekaluk** [comment]
For expediency, I changed nyccouncilmatic.{co,com,net} to CNAME nyccouncilmatic.org

**Comment by rchekaluk** [comment]
@davidmooreppf I would suggest that @derekeder establish and maintain a wiki page(s) for nyccouncilmatic operations at https://github.com/opengovernment/ops/wiki/_pages

**Comment by derekeder** [comment]
Ok we're good to go on this.
