### ISSUE TITLE
process for adding NYC elected officials not in OCD 

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#56]
What's your preference for adding more folks, e.g. the Mayor? Just update this issue with as many [Person Object](http://docs.opencivicdata.org/en/latest/data/person.html) details as possible? Basically name, title, photo, link. This would be about ten people, added once. 

Realize they won't easily be listed off /council_members, but would like them to be findable off /search. Some visitors won't know the difference b/w citywide electeds & council members, of course, and some citywide electeds will be participating in our comment program.

**Comment by derekeder** [comment]
This is done
