### ISSUE TITLE
Is the the internal bill id the most important information element

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-councilmatic#61]
In listings of bills, the bill identifier has the highest visual priority. This seems like an insider's piece of information that does not help users understand what a bill is.

**Comment by davidmooreppf** [comment]
So taking an [Intro](http://nyc-councilmatic.datamade.us/legislation/int-753-2015/) at random -

I recall @cathydeng was going to take a pass at taking the identifier out of h1 and trying to highlight the second half of the title, which has the relevant info.

**Comment by davidmooreppf** [comment]
Ah my bad, you were saying in listings, e.g. from search. Was going to file an issue on that as well. 

Finding this [Intro](http://nyc-councilmatic.datamade.us/legislation/int-846-2015/) from the attached image of search results for "solar" would be ideal: 

<img width="925" alt="solar_nyc" src="https://cloud.githubusercontent.com/assets/116819/10050994/252881d2-61ed-11e5-89d2-856f4953c519.png">

**Comment by fgregg** [comment]
I'm think we are talking about different things. In the listing pages, I think the "Introduction FOO_BAR" has to much visual prominence for an almost meaningless signifier.

**Comment by davidmooreppf** [comment]
Ha I was only initially confused, that's what I meant as well. De-emphasizing the identifier in the design and trying to highlight the relevant words from the item's title.

**Comment by cathydeng** [comment]
@fgregg agreed. I will make the bill identifier smaller, & description more prominent.

someone had good feedback on the descriptions all looking the same (#60) - perhaps we can do some naive text processing to highlight/bold the terms following the consistent canned text. for example:

before: A Local Law to amend the administrative code of the city of New York, in relation to amending the definition of harassment to include certain buyout offers 
after: A Local Law to amend the **administrative code** of the city of New York, in relation to **amending the definition of harassment to include certain buyout offers**

perhaps we'd also want to list the committee(s) that had control of the bill throughout its history, to serve as a pseudo-topic label?

**Comment by cathydeng** [comment]
ok, final action items for this issue:
- [x] less visual prominence for bill identifier
- [x] show committees involved (other than NY city council) as pseudo topic label
- [x] more visual prominence for description

not going to bold useful keywords in description (#60) b/c we are now drawing the eyes to topic tags, & I think it'd add visual clutter - not worth the work
