### ISSUE TITLE
Action order seems not right.

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-councilmatic#62]
See, for example http://nyc-councilmatic.datamade.us/legislation/int-682-2015/ where it appears that an amendment was proposed after the amendment was approved.

**Comment by cathydeng** [comment]
this is the same order as the ocd api (http://ocd.datamade.us/ocd-bill/b943d642-b7e6-4910-94e7-fecd121e4c48/) & legistar (http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2230883&GUID=4D870FC4-85A9-4228-BCC4-3E8DCBC26326)

is it possible that the order is wrong on legistar? say, that stuff within a day is listed in reverse order?
