### ISSUE TITLE
Should committee pages link back to legistar source?

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-councilmatic#65]

**Comment by cathydeng** [comment]
ya this would be nice. the ocd api currently has a url to a generic listing on legistar, under `sources` ([example](http://ocd.datamade.us/ocd-organization/96d21910-d833-4011-9854-2fadaaae920a/)). we could add this if we had a committee page as the source url.

**Comment by fgregg** [comment]
K. open up issue.

On Wed, Sep 23, 2015 at 10:04 AM, Cathy Deng notifications@github.com
wrote:

> ya this would be nice. the ocd api currently has a generic link to a
> legistar listing, under committee source (example
> http://ocd.datamade.us/ocd-organization/96d21910-d833-4011-9854-2fadaaae920a/).
> we could add this if we had a committee page as the source url.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/65#issuecomment-142631330
> .

## 

773.888.2718

**Comment by fgregg** [comment]
Cathy, the sources link for committee pages now links to a legistar detail page.

http://ocd.datamade.us/ocd-organization/1befe8cb-6337-488e-a5d8-384712ef457a/
