### ISSUE TITLE
Is bill history the most important thing about the bill

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-councilmatic#68]
More important than bill text, sponsors, documents, or comments?

Seems like current status, bill text, prime sponsor, and next time it will be acted on are more important.

**Comment by cathydeng** [comment]
yeah good point, this was an open question derek & I had, that we never opened an issue for
- re: bill text, should we feature this tab over bill history? thoughts @davidmooreppf?
- re: primary sponsor, I was going to add it to the top pane above the tabs
- re: next time it will be acted on, I haven't tied events to entities yet (#55)

**Comment by davidmooreppf** [comment]
Good points all. 

I think bill text should stay behind a tab, that makes the most sense to me. 

Great re: primary sponsor in top pane. 

Yeah, that was going to be my simple suggestion, displaying whatever's known for committee hearings: 
- If item is in committee, then display next committee date if known. If not known in system, display copy like: "Next public meeting for this committee has not yet been published on official city government website." Option of linking to Committee page on Legistar, but if it's not published to be scraped, then not much help really. 
- If item is not in committee, goal is to display help text about what it means for it to be assigned to entire city council, and how often that results in hearings with meaningful actions. I've added that to my help text list.

**Comment by cathydeng** [comment]
summary/action items after discussing today:
- **I'll add primary sponsor to top pane**
- I'll hold off tying in events until higher priority issues are resolved, & get back to it if we have time
- I'll keep bill history as primary tab b/c it's less overwhelming than bill text
