### ISSUE TITLE
homepage search vs. /search returns

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#69]
From some user testing - from homepage, he searched "solar" and got less-helpful results :: 

http://nyc-councilmatic.datamade.us/search/?q=solar&q=

... from /search, he got this better results page :: 

http://nyc-councilmatic.datamade.us/search/?q=solar

... the second result there is generally more interesting than first, so maybe eventually we could weight the Intros by views or "featured"-ness. But for now, what are default filters on homepage search?  &q etc.

**Comment by cathydeng** [comment]
oh yeah, this is b/c I broke the search field on the home page when I was moving stuff around. noted during some user-feedback we did, #60. I'll fix
