### ISSUE TITLE
two initial featured bills for homepage

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#70]
I know we don't have designs for these types of pages now - let's chat over whether these all need to fit into boxes, or if we'll create pages such as /featured. All of the below is very much editable. 

By the way, these may change pretty often as more verified council members join, so having me be able to merge edits via GitHub is probably most efficient process? I would guess that's the expected workflow already. 

I'll have to find graphics for these, still. Let's chat over whether it should be photos or images. 

Traffic Congestion & For-Hire Vehicles Study

http://nyc-councilmatic.datamade.us/legislation/int-847-2015/

... some copy I threw together as summary, can be edited or hidden to expand: 

On Aug. 10th, Mayor de Blasio signed into law a bill sponsored by Council Member Ydanis Rodriguez and nine others, "to conduct a study on how growth in the taxi and for-hire vehicle industries has impacted traffic, air quality, noise, and public health." On September 16th, the Wall Street Journal reported that Uber, one major participant in the study's Advisory Group, would release different guidelines about how long such a study should take. On Sept. 17th, at a hearing by Manhattan Borough President Gale Brewer, Uber reiterated that a study should take longer than four months, but didn't provide extensive driver data in response to Brewer's oversight questions. For more info on next steps, ask your council member's office for an update and share the response in a comment on this bill page. The NYC Council Committee on Transportation does not yet have any hearings scheduled for October 2015, but when it does, its agenda will be viewable on NYC Councilmatc.

MIsc. links for my reference :: 

http://www.capitalnewyork.com/article/city-hall/2015/09/8577153/uber-fight-city-hall-overshadows-congestion-hearing

http://www.wsj.com/articles/uber-vs-city-hall-round-two-1442451813

---

Police Body Cameras Task Force

http://nyc-councilmatic.datamade.us/legislation/int-607-2014/

On June 29th, 2015, the Committee on Public Safety held a hearing on this bill sponsored by Council Member Jumaane Williams and ten others, to "create a task force to study the issues involved with requiring New York City Police Department officers to wear body-worn cameras that record their activities." At the hearing, official minutes report that this was one of nine Introductions (bills) for police reforms considered, which were all "laid over" - that is, no further action or vote was taken at this time. Council Member Williams had previously published an op-ed on April 10th, 2015 declaring his support for body cameras on all police: "When implemented properly, body cameras are neutral observers and can protect citizens and officers alike." For more info on next steps, ask your council member's office for an update and share the response in a comment on this bill page. The Committee on Public Safety does not yet have any hearings scheduled for October 2015, but when it does, its agenda will be viewable on NYC Councilmatic. 

My reference :: 

http://www.nydailynews.com/new-york/city-council-members-put-body-cameras-article-1.2180212

**Comment by cathydeng** [comment]
yay this is great!

I think we should definitely have featured bills on the home page, although as we start to update/accumulate featured bills, we could also have a page dedicated to featured bills & have a 'see more` button.

& yeah updating static content is totally fine - either updating on github or copy/pasting into this issue works.

also, cool if I shorten the copy here? I'm worried about scaring people away with a large blob of text.

**Comment by davidmooreppf** [comment]
Oh totally - realize copy that long can't go on homepage. Thought of it maybe on a /featured or /about/featured/bill page or whatever.

I don't know if we have time for my fuller copy to live on their regular bill pages, in their own box, I think below the official plain-language summary? It would have to be hard-coded into those two pages, I reckon. 

But if we can add a box I could even add info about who's listening to the public discussion from participating verified council offices, groups that are active on the issue, etc. , and any new public hearings or news articles.

**Comment by cathydeng** [comment]
@davidmooreppf just saw your comment on photos - since the site is text-heavy, it'd be _great_ to have more imagery. do you have them?

**Comment by cathydeng** [comment]
@davidmooreppf would it be possible to better tie the traffic study description to the content we have on the bill page? e.g. do we know why the bill was laid over, how it was amended, how uber impacted the bill's history?

**Comment by cathydeng** [comment]
shortened the bill blurbs - how does this look?

**Study on Traffic Congestion & For-Hire Vehicles**
Mayor de Blasio has claimed that ride share services have caused traffic problems. In August, he approved a bill to conduct a study on how growth in the for-hire industry has impacted traffic, air quality, noise, & public health. Uber [accused the city of moving too fast](http://www.capitalnewyork.com/article/city-hall/2015/09/8577153/uber-fight-city-hall-overshadows-congestion-hearing), asserting that it should take longer than the four months provided and [commissioning its own study on the issue](http://www.wsj.com/articles/uber-vs-city-hall-round-two-1442451813).

View bill details ->

**Task force on Police Body Cameras**
After Walter Scott’s death, [many called for police officers to wear body cameras](http://www.nydailynews.com/new-york/city-council-members-put-body-cameras-article-1.2180212) to record their activities. In June, the city council introduced a bill to create a task force for studying issues related to police body cameras. This was one of nine police reform-related bills considered during a hearing on 6/29, held by the Committee on Public Safety. At the hearing, all nine bills were laid over, meaning that no further actions or votes were taken.

View bill details ->

**Comment by davidmooreppf** [comment]
Used creative-commons Google image search to find two attached. 

The congestion description you wrote is great. 

On the police body cameras, let's add some NYC specifics to first line: 

After the deaths of Walter Scott in South Carolina and Eric Garner in Staten Island, NY, many called for police officers to wear body cameras to record their activities. 

... I'll try to get more info on task force next steps from CM Williams' office for next week, but that works for now. Great edits.

**Comment by davidmooreppf** [comment]
Attached, rather. Ay don't know if the police one will shrink, and I don't know if the traffic one is sufficiently high-quality, source was Move NY flyer: 

https://movenewyork.files.wordpress.com/2015/02/2015-mny-final-ex-sum-copy_page_1.jpg

... can find another, e.g. ::

https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/New_York_Prius_cab.JPG/220px-New_York_Prius_cab.JPG

![nypd_image](https://cloud.githubusercontent.com/assets/116819/10083864/4eba1132-62ce-11e5-8865-5f853a1c8c0a.jpg)
![moveny_image](https://cloud.githubusercontent.com/assets/116819/10083865/4ec186ec-62ce-11e5-8970-0274504dd480.png)
