### ISSUE TITLE
Bills that have been approved by committee but not by council shoudn't have an "approved" status

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-councilmatic#80]
http://nyc-councilmatic.datamade.us/legislation/lu-286-2015/ should have an "active" status, not an approved status.

**Comment by cathydeng** [comment]
active is stuff that hasn't been approved but not stale, approved is stuff that got thru committee, passed is stuff signed into law. is the issue that it's not apparent that approved != complete & that there's still a ways to go? if so, progress bars (#28) should help

**Comment by fgregg** [comment]
Yes, the issue is that approved seems like a terminal status.

Progress bars will def help. It would also help if, in bill history, the approval of city council was called "passed" and not "approved"

**Comment by fgregg** [comment]
See #81

**Comment by fgregg** [comment]
Or do you want to reserve "passed" for things that are all the way through, including signed by mayor?

**Comment by cathydeng** [comment]
hm. how about we have 2 diff 'statuses' - (1) active/stale/final label & (2) progress bar where applicable

for (1), final is anything that has reached the final status (perhaps we could have the wording vary, 'passed' or 'filed' based on legislation type), stale is everything that hasn't reached final status & hasn't had activity in 2 months, & active is everything else. this would take care of #81 & #76

for (2), we can have custom progress bars for the relevant types of bills, e.g. introduction would have (a) introduced (b) approved by council & (c) approved by mayor (while it is possible for mayor to veto & for council to override veto for a bill to get passed, I don't see any vetos among the action data, so I think it'd be safe to assume that these 3 steps are required). we can leave out progress bars for oversights, tours, etc

thoughts?

**Comment by fgregg** [comment]
I think it's better to have fewer states.  For legislation, I think it
should be
- Active
- Stale
- Passed/Failed

I think we should not show non legislation in this version like Oversights,
I think we need to do more thinking to figure out how and where to show non
legislation. This non legislation does not really have a a legislative
status.

On Fri, Sep 25, 2015 at 8:57 AM, Cathy Deng notifications@github.com
wrote:

> hm. how about we have 2 diff statuses - (1) active/stale/final & (2)
> progress bar
> 
> for (1), final is anything that has reached the final status (perhaps we
> could have the wording vary, 'passed' or 'filed' based on legislation
> type), stale is everything that hasn't reached final status & hasn't had
> activity in 2 months, & active is everything else
> 
> for (2), we can have custom progress bars for the relevant types of bills,
> e.g. introduction would have (a) introduced (b) approved by council & (c)
> approved by mayor (while it is possible for mayor to veto & for council to
> override veto for a bill to get passed, I don't see any vetos among the
> action data, so I think it'd be safe to assume that these 3 steps are
> required). we can leave out progress bars for oversights, tours, etc
> 
> thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/80#issuecomment-143231196
> .

## 

773.888.2718

**Comment by cathydeng** [comment]
I think we are saying the same thing - I meant one type of status, active/stale/passed (we don't have failed), & then a progress bar indicating steps. I think the progress bar is still useful, e.g. if something is stale it'd be helpful to see what step it left off on. I'd be cool with hiding stuff like oversights/tours, as I think it does make the website more confusing. thoughts @davidmooreppf?

**Comment by cathydeng** [comment]
as an alternative to hiding oversights/tours, we could also make them look visually different from legislation in a listing, e.g. add an icon, smaller/lighter heading, remove irrelevant status label. this could be a quick & easy way to resolve #71
