### ISSUE TITLE
Vincent Ignizio is not a current member

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-councilmatic#84]
As you can see here http://ocd.datamade.us/ocd-organization/0f63aae8-16fd-4d3c-b525-00747a482cf9/ his membership ended in July.

**Comment by cathydeng** [comment]
pretty sure this is bc people haven't finished loading - for the council members listing it grabs the most recent person for each post

**Comment by fgregg** [comment]
there is not a more recent person in that post, it's currently vacant.

On Fri, Sep 25, 2015 at 5:41 PM, Cathy Deng notifications@github.com
wrote:

> pretty sure this is bc people haven't finished loading - for the council
> members listing it grabs the most recent person for each post
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/84#issuecomment-143369482
> .

## 

773.888.2718

**Comment by cathydeng** [comment]
ooo ok. I'll change the logic from most recent to most recent & within curren leg sesh

**Comment by fgregg** [comment]
that won't quite work either, he quit during this legislative session.

On Fri, Sep 25, 2015 at 5:46 PM, Cathy Deng notifications@github.com
wrote:

> ooo ok. I'll change the logic from most recent to most recent & within
> curren leg sesh
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datamade/nyc-councilmatic/issues/84#issuecomment-143370144
> .

## 

773.888.2718

**Comment by fgregg** [comment]
You could jsut check that they don't have an end date

On Fri, Sep 25, 2015 at 5:48 PM, Forest Gregg fgregg@uchicago.edu wrote:

> that won't quite work either, he quit during this legislative session.
> 
> On Fri, Sep 25, 2015 at 5:46 PM, Cathy Deng notifications@github.com
> wrote:
> 
> > ooo ok. I'll change the logic from most recent to most recent & within
> > curren leg sesh
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/datamade/nyc-councilmatic/issues/84#issuecomment-143370144
> > .
> 
> ## 
> 
> 773.888.2718

## 

773.888.2718

**Comment by fgregg** [comment]
On http://nyc.councilmatic.org/council-members/, it would be ideal to show District 51, and to show that it was vacant. Otherwise folks might get idea that there are 50 districts.
