### ISSUE TITLE
display "Notes" from Legistar pages on member profile pages

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#88]
Enhancement here - cc @derekeder, @fgregg 

Individual member's pages on Legistar, linked from our pages, have useful Notes. E.g., what neighborhoods are in a district, caucus info - both are hugely helpful & meaningful. It varies from member to member a lot, though, see below. 

So notes are on Legistar member pages, e.g. see [Chin](http://legistar.council.nyc.gov/PersonDetail.aspx?ID=42514&GUID=D275DF50-6FAE-446D-B1E7-8AE61BC1C0B8&Search=), but don't seem to be accommodated in [OCD person](http://docs.opencivicdata.org/en/latest/api/search.html#person-search) that I can find. So we may not have this info via OCD. 

This info shouldn't change too much, but realize adding stuff that's not in OCD always requires a bit of maintenance, that'll be our responsibility to watch its currentness & accuracy. 

Goal is to display note in full, somehow, on our member pages. If we can find a way to display it, even if hidden behind a pop-out, would you want it in a Google doc or a spreadsheet? 

District 1 - Council Member - Democrat ~ Chair, Committee on Aging ~ Margaret Chin was elected to the New York City Council in 2010, as the representative for District 1, lower Manhattan. Margaret is a proud member of the Progressive Caucus, and the Women's Caucus. Margaret has twice been elected by her colleagues to serve as an executive member of the Black, Latino, and Asian Caucus.

---

Curveball is, some member pages have not much info in notes, e.g. [Corey Johnson](http://legistar.council.nyc.gov/PersonDetail.aspx?ID=125479&GUID=32D93D23-C637-4D79-B96E-47F3D0472147&Search=), but rather on their council.nyc.gov page - see [Corey Johnson](http://council.nyc.gov/d3/html/members/home.shtml) there. E.g. "Hell’s Kitchen, Chelsea, the West Village, and parts of Flatiron, SoHo and the Upper West Side." 

We can manually pull out the neighborhood & caucus info, let me know if you'd like that in a spreadsheet, and if you'd like the neighborhood names in their own cells or just comma-separated in a cell. We'll do the manual work to take it off your plate.

**Comment by fgregg** [comment]
I think we have existing issues for all of these bits of information, or are already capturing this information
- We already are displaying district
- We are already showing, under the committee tab, chairmanships and committee memberships
- We are already capturing, but not showing the party, #87
- We are capturing, but now showing tenure, and have an issue for showing this #73 
- We have an issue for using the bio #59 

Is there any other piece of information in these notes that we are not capturing or is not covered by an existing issue?

**Comment by davidmooreppf** [comment]
My bad on #59, I didn't see that existed. Good stuff. 

So just #86 can stay open.

**Comment by fgregg** [comment]
Oh, we don't have caucuses. It would be good if you made a spreadsheet of that.

**Comment by davidmooreppf** [comment]
Will do - format? One column named Caucus, and comma-separated values in each? 

E.g. for Chin: Progress, Women's 

... or separate cells? Obvs. whatever's best for you.
