### ISSUE TITLE
homepage suggestion- display Events above Recently Passed

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#89]
Just a simple flip suggestion here-  on homepage, I suggest displaying "Events" below featured bills and above Recently Passed

It's awesome info, it changes the feel of the app in a great way (helpful notice ahead of time!), and I think it's more likely be of interest than Recently Passed. Search - featured - events - recent is a great flow.

The info in #83 from Cathy are great ideas too, would love to display those down the line near Events. 

Let me know what you think, Cathy.

**Comment by cathydeng** [comment]
ya I agree - someone else I showed it to had the same feedback. I'll make the change
