### ISSUE TITLE
diff types of organizations should have diff classifications

### ISSUE THREAD

**Issue by cathydeng** [datamade/nyc-councilmatic#9]
committees, subcommittees, & task forces are currently all categorized as a committee in the open civic data api

examples:
[subcommittee](http://api.opencivicdata.org/ocd-organization/302ed59a-2a51-4440-af5e-3c288ef78ed6/)
[task force](http://api.opencivicdata.org/ocd-organization/0f5bcb75-15a1-496d-bcad-b2ca15368046/)

**Comment by fgregg** [comment]
Fixed by https://github.com/opencivicdata/scrapers-us-municipal/commit/9e75cf4a0c887cea30da7e82d227f5514faeb454
