### ISSUE TITLE
Alderman's detail pages

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-councilmatic#92]
Things that could be good to have an alderman's page
- Tenure, and indication of tenure rank
- Amount in war chest, and link to illinoissunshine (maybe this is a widget)
- Caucus membership
- % voting with mayor
- Most similar voting pattern (show similar alderman)
- Sponsored legislation
- Success rate of sponsored legislation
- Map of ward
- Contact info
- Committee chairs
- Most recent newsletter
- % Vote share last election

**Comment by cathydeng** [comment]
wrong repo?

**Comment by fgregg** [comment]
Woops! sorry

**Comment by davidmooreppf** [comment]
Oh I love this stuff, by the way. Had the percentage indicators on OpenCongress. Hope we'll eventually get there in NYC as well.
