### ISSUE TITLE
site title in the browser chrome

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#93]
Preview site in browser tab is currently pulling the homepage title "Keep tabs on what..." , maybe optimized as: 

NYC City Council: Councilmatic - Track bills, votes, and members.

Maybe this is part of #39, didn't mean to duplicate. Maybe production site has a diff. strategy, don't mean to be dense. Just filing it as I caught it.

**Comment by cathydeng** [comment]
already updated this - changes just haven't been deployed. the site title is now '[page-name] - NYC Councilmatic'
