### ISSUE TITLE
email list embed for PPF's Action Network mailing lists - first pass

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#95]
Goal is for visitors to /about page to be able to easily sign up for updates by entering email 

Forgive my ham-handedness here, but on old splash page [index](https://github.com/opengovernment/splash.nyccouncilmatic.com/blob/master/index.html) over on our GitHub, I see ::

```
<nav>
    <ul class="level">
      <li class="active" data-type="individual">
        <a href="splash.html#" id="individual-signup">Individual</a>
        <i class="icon-angle-down"></i>
      </li>
      <li class="" data-type="elected_official">
        <a href="splash.html#" id="official-signup">Elected Official</a>
        <i class="icon-angle-down"></i>
      </li>
      <li data-type="organization">
        <a href="splash.html#" id="organization-signup">Organization or Media</a>
        <i class="icon-angle-down"></i>
      </li>
    </ul>
  </nav>
  <form action="http://subscribe.askthem.io/cgi-bin/notify-me-nyccouncilmatic" class='splash-form'>
    <input type="email" name="email" id="email" placeholder="E-mail">
    <input type="text" name="zipcode" id="zipcode" placeholder="Zipcode (optional)">
    <input type="hidden" name="notify_type" id="notify_type" value="individual">
    <input type="hidden" name="notify_source" id="notify_source" value="splash">
    <input type="submit" id="dynamic-button" value="Notify Me" class="cta-pill">
    <div id="dynamic-link">
    </div>
  </form>
```

... will that work for launch? We can check with Rob Chekaluk over in that repo if need be. cc @derekeder. I think it should be working on AskThem's end. 

Doesn't nec. need to have options for invidiual, elected official, and media/organization, but preserving that is fine.

**Comment by derekeder** [comment]
@davidmooreppf  Think we're missing some javascript and css to get this form to work. Do you have a reference to the full working signup form.

**Comment by davidmooreppf** [comment]
Unfort the splash page at nyccouncilmatic.org was taken down and there's not one on AskThem anywhere. Asking Rob over there in that repo now.
