### ISSUE TITLE
wondering about "filter results" behavior w/r/t browsing more pages

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#96]
From /search, if I pop open filter options and select resolutions, I see one page of only resolutions. But if I click ahead to second page, it adds-in other types again. 

We don't have time to rework filtering, probably, but is that intentional? What's possible by way of help text for how filtering options work for launch?

Could explain that there's no way to "clear" your selected filter options now, that a new search is needed to go backwards - e.g. to uncheck "resolution", if you selected that previously. 

Should that pop-out be renamed Advanced Search, if it doesn't filter through pagination?

**Comment by derekeder** [comment]
Ah yah this is something we noticed too. Issue is over at #106
