### ISSUE TITLE
roll call info - present, absent - in NYC OCD? Just looking ahead. 

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-councilmatic#97]
Something to examine for explainers w/ our council partners, why there aren't aye/nay votes recorded in Legistar for Intros that with actions: Pass. 

NYC Legistar roll calls seem to live in modal windows on Legistar - finding an "Approved" Intro at random, here's the [page](http://legistar.council.nyc.gov/MeetingDetail.aspx?ID=435250&GUID=66D3C589-6F39-4756-8CD5-3F370DFC39E9&Options=&Search=) for the action where it Passed, go into Meeting Details, and the Action Details link to Roll Call simply shows four members present and one absent, not 'aye/nay/abstain' etc. Another Intro w/ same on [Legistar](http://legistar.council.nyc.gov/MeetingDetail.aspx?ID=434496&GUID=EAC6A48F-8F70-41D0-96BE-4FF3A5772E92&Options=&Search=).

I guess for now I'm wondering if NYC OCD captures those roll call modals - present, absent, etc.? Doesn't seem so, as they're not on Councilmatic [Intro pages](http://nyc.councilmatic.org/legislation/int-903-2015/). 

Will dig into this and write help copy for @cathydeng.

**Comment by davidmooreppf** [comment]
Ah, was writing this quickly on the plane - those are actual roll-call present/absent calls for the committee event, not votes on action. Those are something, but members often leave hearings. 

Here's an example of an enacted Intro on Legistar [event details page](http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2402123&GUID=164871EA-F727-4020-9047-1E9EDF17BB04&Options=Advanced&Search=). Includes "affirmative" or other response for every present council member, but doesn't include counts. 

So that's an enhancement, displaying totals & pie charts of vote counts for enacted Intros. That info would eventually live on the "Passed" action on [Councilmatic page](http://nyc.councilmatic.org/legislation/int-847-2015/) for that same intro, under History tab.

**Comment by fgregg** [comment]
If you look at the action details for "passed council" you will see the individual votes. We capturing this in OCD.

**Comment by fgregg** [comment]
See http://ocd.datamade.us/ocd-bill/5a9d30bd-b97d-4054-a030-d09a04d6cad3/

and http://ocd.datamade.us/ocd-vote/663c17f0-330c-41b1-bc1e-5822afa1aaa8/
